package com.wangli.data.analysis.ar.adc.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.analysis.ar.adc.module.CorpOrder;
import com.wangli.data.analysis.ar.adc.module.CorpOrderExample;
import java.sql.SQLException;
import java.util.List;

public class CorpOrderDAOImpl implements CorpOrderDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public CorpOrderDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int countByExample(CorpOrderExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("corp_order.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int deleteByExample(CorpOrderExample example) throws SQLException {
        int rows = sqlMapClient.delete("corp_order.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int deleteByPrimaryKey(Integer orderId) throws SQLException {
        CorpOrder key = new CorpOrder();
        key.setOrderId(orderId);
        int rows = sqlMapClient.delete("corp_order.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void insert(CorpOrder record) throws SQLException {
        sqlMapClient.insert("corp_order.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void insertSelective(CorpOrder record) throws SQLException {
        sqlMapClient.insert("corp_order.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public List selectByExample(CorpOrderExample example) throws SQLException {
        List list = sqlMapClient.queryForList("corp_order.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public CorpOrder selectByPrimaryKey(Integer orderId) throws SQLException {
        CorpOrder key = new CorpOrder();
        key.setOrderId(orderId);
        CorpOrder record = (CorpOrder) sqlMapClient.queryForObject("corp_order.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByExampleSelective(CorpOrder record, CorpOrderExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("corp_order.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByExample(CorpOrder record, CorpOrderExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("corp_order.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByPrimaryKeySelective(CorpOrder record) throws SQLException {
        int rows = sqlMapClient.update("corp_order.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByPrimaryKey(CorpOrder record) throws SQLException {
        int rows = sqlMapClient.update("corp_order.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private static class UpdateByExampleParms extends CorpOrderExample {
        private Object record;

        public UpdateByExampleParms(Object record, CorpOrderExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}