package com.wangli.data.analysis.ar.adc.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.analysis.ar.adc.module.CorpChannelTag;
import com.wangli.data.analysis.ar.adc.module.CorpChannelTagExample;
import java.sql.SQLException;
import java.util.List;

public class CorpChannelTagDAOImpl implements CorpChannelTagDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public CorpChannelTagDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int countByExample(CorpChannelTagExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("corp_channel_tag.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int deleteByExample(CorpChannelTagExample example) throws SQLException {
        int rows = sqlMapClient.delete("corp_channel_tag.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        CorpChannelTag key = new CorpChannelTag();
        key.setId(id);
        int rows = sqlMapClient.delete("corp_channel_tag.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void insert(CorpChannelTag record) throws SQLException {
        sqlMapClient.insert("corp_channel_tag.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void insertSelective(CorpChannelTag record) throws SQLException {
        sqlMapClient.insert("corp_channel_tag.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public List selectByExample(CorpChannelTagExample example) throws SQLException {
        List list = sqlMapClient.queryForList("corp_channel_tag.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public CorpChannelTag selectByPrimaryKey(Integer id) throws SQLException {
        CorpChannelTag key = new CorpChannelTag();
        key.setId(id);
        CorpChannelTag record = (CorpChannelTag) sqlMapClient.queryForObject("corp_channel_tag.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByExampleSelective(CorpChannelTag record, CorpChannelTagExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("corp_channel_tag.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByExample(CorpChannelTag record, CorpChannelTagExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("corp_channel_tag.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByPrimaryKeySelective(CorpChannelTag record) throws SQLException {
        int rows = sqlMapClient.update("corp_channel_tag.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByPrimaryKey(CorpChannelTag record) throws SQLException {
        int rows = sqlMapClient.update("corp_channel_tag.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private static class UpdateByExampleParms extends CorpChannelTagExample {
        private Object record;

        public UpdateByExampleParms(Object record, CorpChannelTagExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}