package com.wangli.data.analysis.ar.adc.dao;

import com.wangli.data.analysis.ar.adc.module.CorpChannelTag;
import com.wangli.data.analysis.ar.adc.module.CorpChannelTagExample;
import java.sql.SQLException;
import java.util.List;

public interface CorpChannelTagDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int countByExample(CorpChannelTagExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int deleteByExample(CorpChannelTagExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    void insert(CorpChannelTag record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    void insertSelective(CorpChannelTag record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    List selectByExample(CorpChannelTagExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    CorpChannelTag selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByExampleSelective(CorpChannelTag record, CorpChannelTagExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByExample(CorpChannelTag record, CorpChannelTagExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByPrimaryKeySelective(CorpChannelTag record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_channel_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByPrimaryKey(CorpChannelTag record) throws SQLException;
}