package com.wangli.data.analysis.ar.adc.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.analysis.ar.adc.module.DeviceAppInfo;
import com.wangli.data.analysis.ar.adc.module.DeviceAppInfoExample;
import java.sql.SQLException;
import java.util.List;

public class DeviceAppInfoDAOImpl implements DeviceAppInfoDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public DeviceAppInfoDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public int countByExample(DeviceAppInfoExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("device_app_info.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public int deleteByExample(DeviceAppInfoExample example) throws SQLException {
        int rows = sqlMapClient.delete("device_app_info.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public int deleteByPrimaryKey(Long id) throws SQLException {
        DeviceAppInfo key = new DeviceAppInfo();
        key.setId(id);
        int rows = sqlMapClient.delete("device_app_info.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public void insert(DeviceAppInfo record) throws SQLException {
        sqlMapClient.insert("device_app_info.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public void insertSelective(DeviceAppInfo record) throws SQLException {
        sqlMapClient.insert("device_app_info.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public List selectByExample(DeviceAppInfoExample example) throws SQLException {
        List list = sqlMapClient.queryForList("device_app_info.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public DeviceAppInfo selectByPrimaryKey(Long id) throws SQLException {
        DeviceAppInfo key = new DeviceAppInfo();
        key.setId(id);
        DeviceAppInfo record = (DeviceAppInfo) sqlMapClient.queryForObject("device_app_info.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public int updateByExampleSelective(DeviceAppInfo record, DeviceAppInfoExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("device_app_info.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public int updateByExample(DeviceAppInfo record, DeviceAppInfoExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("device_app_info.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public int updateByPrimaryKeySelective(DeviceAppInfo record) throws SQLException {
        int rows = sqlMapClient.update("device_app_info.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public int updateByPrimaryKey(DeviceAppInfo record) throws SQLException {
        int rows = sqlMapClient.update("device_app_info.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    private static class UpdateByExampleParms extends DeviceAppInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, DeviceAppInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}