package com.wangli.data.analysis.ar.adc.dao;

import com.wangli.data.analysis.ar.adc.module.DeviceAppAddInfo;
import com.wangli.data.analysis.ar.adc.module.DeviceAppAddInfoExample;
import java.sql.SQLException;
import java.util.List;

public interface DeviceAppAddInfoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_add_info
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    int countByExample(DeviceAppAddInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_add_info
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    int deleteByExample(DeviceAppAddInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_add_info
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    int deleteByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_add_info
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    void insert(DeviceAppAddInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_add_info
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    void insertSelective(DeviceAppAddInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_add_info
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    List selectByExample(DeviceAppAddInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_add_info
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    DeviceAppAddInfo selectByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_add_info
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    int updateByExampleSelective(DeviceAppAddInfo record, DeviceAppAddInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_add_info
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    int updateByExample(DeviceAppAddInfo record, DeviceAppAddInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_add_info
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    int updateByPrimaryKeySelective(DeviceAppAddInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_add_info
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    int updateByPrimaryKey(DeviceAppAddInfo record) throws SQLException;
}