package com.wangli.data.analysis.ar.adc.dao;

import com.wangli.data.analysis.ar.adc.module.DeviceActiveLog;
import com.wangli.data.analysis.ar.adc.module.DeviceActiveLogExample;
import java.sql.SQLException;
import java.util.List;

public interface DeviceActiveLogDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int countByExample(DeviceActiveLogExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int deleteByExample(DeviceActiveLogExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int deleteByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    void insert(DeviceActiveLog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    void insertSelective(DeviceActiveLog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    List selectByExample(DeviceActiveLogExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    DeviceActiveLog selectByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByExampleSelective(DeviceActiveLog record, DeviceActiveLogExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByExample(DeviceActiveLog record, DeviceActiveLogExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByPrimaryKeySelective(DeviceActiveLog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByPrimaryKey(DeviceActiveLog record) throws SQLException;
}