package com.wangli.data.analysis.ar.adc.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.analysis.ar.adc.module.DeviceActiveLog;
import com.wangli.data.analysis.ar.adc.module.DeviceActiveLogExample;
import java.sql.SQLException;
import java.util.List;

public class DeviceActiveLogDAOImpl implements DeviceActiveLogDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public DeviceActiveLogDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int countByExample(DeviceActiveLogExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("device_active_log.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int deleteByExample(DeviceActiveLogExample example) throws SQLException {
        int rows = sqlMapClient.delete("device_active_log.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int deleteByPrimaryKey(Long id) throws SQLException {
        DeviceActiveLog key = new DeviceActiveLog();
        key.setId(id);
        int rows = sqlMapClient.delete("device_active_log.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void insert(DeviceActiveLog record) throws SQLException {
        sqlMapClient.insert("device_active_log.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void insertSelective(DeviceActiveLog record) throws SQLException {
        sqlMapClient.insert("device_active_log.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public List selectByExample(DeviceActiveLogExample example) throws SQLException {
        List list = sqlMapClient.queryForList("device_active_log.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public DeviceActiveLog selectByPrimaryKey(Long id) throws SQLException {
        DeviceActiveLog key = new DeviceActiveLog();
        key.setId(id);
        DeviceActiveLog record = (DeviceActiveLog) sqlMapClient.queryForObject("device_active_log.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByExampleSelective(DeviceActiveLog record, DeviceActiveLogExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("device_active_log.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByExample(DeviceActiveLog record, DeviceActiveLogExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("device_active_log.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByPrimaryKeySelective(DeviceActiveLog record) throws SQLException {
        int rows = sqlMapClient.update("device_active_log.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByPrimaryKey(DeviceActiveLog record) throws SQLException {
        int rows = sqlMapClient.update("device_active_log.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table device_active_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private static class UpdateByExampleParms extends DeviceActiveLogExample {
        private Object record;

        public UpdateByExampleParms(Object record, DeviceActiveLogExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}