package com.wangli.data.analysis.ar.adc.dao;

import com.wangli.data.analysis.ar.adc.module.DeviceAppInfo;
import com.wangli.data.analysis.ar.adc.module.DeviceAppInfoExample;
import java.sql.SQLException;
import java.util.List;

public interface DeviceAppInfoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    int countByExample(DeviceAppInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    int deleteByExample(DeviceAppInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    int deleteByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    void insert(DeviceAppInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    void insertSelective(DeviceAppInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    List selectByExample(DeviceAppInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    DeviceAppInfo selectByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    int updateByExampleSelective(DeviceAppInfo record, DeviceAppInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    int updateByExample(DeviceAppInfo record, DeviceAppInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    int updateByPrimaryKeySelective(DeviceAppInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device_app_info
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    int updateByPrimaryKey(DeviceAppInfo record) throws SQLException;
}