package com.wangli.data.analysis.ar.adc.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.analysis.ar.adc.module.DictIdentityStorage;
import com.wangli.data.analysis.ar.adc.module.DictIdentityStorageExample;
import java.sql.SQLException;
import java.util.List;

public class DictIdentityStorageDAOImpl implements DictIdentityStorageDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public DictIdentityStorageDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int countByExample(DictIdentityStorageExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("dict_identity_storage.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int deleteByExample(DictIdentityStorageExample example) throws SQLException {
        int rows = sqlMapClient.delete("dict_identity_storage.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        DictIdentityStorage key = new DictIdentityStorage();
        key.setId(id);
        int rows = sqlMapClient.delete("dict_identity_storage.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void insert(DictIdentityStorage record) throws SQLException {
        sqlMapClient.insert("dict_identity_storage.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void insertSelective(DictIdentityStorage record) throws SQLException {
        sqlMapClient.insert("dict_identity_storage.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public List selectByExample(DictIdentityStorageExample example) throws SQLException {
        List list = sqlMapClient.queryForList("dict_identity_storage.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public DictIdentityStorage selectByPrimaryKey(Integer id) throws SQLException {
        DictIdentityStorage key = new DictIdentityStorage();
        key.setId(id);
        DictIdentityStorage record = (DictIdentityStorage) sqlMapClient.queryForObject("dict_identity_storage.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByExampleSelective(DictIdentityStorage record, DictIdentityStorageExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("dict_identity_storage.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByExample(DictIdentityStorage record, DictIdentityStorageExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("dict_identity_storage.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByPrimaryKeySelective(DictIdentityStorage record) throws SQLException {
        int rows = sqlMapClient.update("dict_identity_storage.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByPrimaryKey(DictIdentityStorage record) throws SQLException {
        int rows = sqlMapClient.update("dict_identity_storage.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private static class UpdateByExampleParms extends DictIdentityStorageExample {
        private Object record;

        public UpdateByExampleParms(Object record, DictIdentityStorageExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}