package com.wangli.data.analysis.ar.adc.dao;

import com.wangli.data.analysis.ar.adc.module.DictDeviceModel;
import com.wangli.data.analysis.ar.adc.module.DictDeviceModelExample;
import java.sql.SQLException;
import java.util.List;

public interface DictDeviceModelDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int countByExample(DictDeviceModelExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int deleteByExample(DictDeviceModelExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int deleteByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    void insert(DictDeviceModel record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    void insertSelective(DictDeviceModel record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    List selectByExample(DictDeviceModelExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    DictDeviceModel selectByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByExampleSelective(DictDeviceModel record, DictDeviceModelExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByExample(DictDeviceModel record, DictDeviceModelExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByPrimaryKeySelective(DictDeviceModel record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByPrimaryKey(DictDeviceModel record) throws SQLException;
}