package com.wangli.data.analysis.ar.adc.dao;

import com.wangli.data.analysis.ar.adc.module.DictIdentityStorage;
import com.wangli.data.analysis.ar.adc.module.DictIdentityStorageExample;
import java.sql.SQLException;
import java.util.List;

public interface DictIdentityStorageDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int countByExample(DictIdentityStorageExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int deleteByExample(DictIdentityStorageExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    void insert(DictIdentityStorage record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    void insertSelective(DictIdentityStorage record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    List selectByExample(DictIdentityStorageExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    DictIdentityStorage selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByExampleSelective(DictIdentityStorage record, DictIdentityStorageExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByExample(DictIdentityStorage record, DictIdentityStorageExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByPrimaryKeySelective(DictIdentityStorage record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_identity_storage
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByPrimaryKey(DictIdentityStorage record) throws SQLException;
}