package com.wangli.data.analysis.ar.adc.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.analysis.ar.adc.module.DictDeviceModel;
import com.wangli.data.analysis.ar.adc.module.DictDeviceModelExample;
import java.sql.SQLException;
import java.util.List;

public class DictDeviceModelDAOImpl implements DictDeviceModelDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public DictDeviceModelDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int countByExample(DictDeviceModelExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("dict_device_model.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int deleteByExample(DictDeviceModelExample example) throws SQLException {
        int rows = sqlMapClient.delete("dict_device_model.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int deleteByPrimaryKey(Long id) throws SQLException {
        DictDeviceModel key = new DictDeviceModel();
        key.setId(id);
        int rows = sqlMapClient.delete("dict_device_model.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void insert(DictDeviceModel record) throws SQLException {
        sqlMapClient.insert("dict_device_model.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void insertSelective(DictDeviceModel record) throws SQLException {
        sqlMapClient.insert("dict_device_model.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public List selectByExample(DictDeviceModelExample example) throws SQLException {
        List list = sqlMapClient.queryForList("dict_device_model.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public DictDeviceModel selectByPrimaryKey(Long id) throws SQLException {
        DictDeviceModel key = new DictDeviceModel();
        key.setId(id);
        DictDeviceModel record = (DictDeviceModel) sqlMapClient.queryForObject("dict_device_model.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByExampleSelective(DictDeviceModel record, DictDeviceModelExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("dict_device_model.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByExample(DictDeviceModel record, DictDeviceModelExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("dict_device_model.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByPrimaryKeySelective(DictDeviceModel record) throws SQLException {
        int rows = sqlMapClient.update("dict_device_model.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByPrimaryKey(DictDeviceModel record) throws SQLException {
        int rows = sqlMapClient.update("dict_device_model.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table dict_device_model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private static class UpdateByExampleParms extends DictDeviceModelExample {
        private Object record;

        public UpdateByExampleParms(Object record, DictDeviceModelExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}