package com.wangli.data.analysis.ar.adc.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.analysis.ar.adc.module.FactAppAddStat;
import com.wangli.data.analysis.ar.adc.module.FactAppAddStatExample;
import java.sql.SQLException;
import java.util.List;

public class FactAppAddStatDAOImpl implements FactAppAddStatDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table fact_app_add_stat
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_add_stat
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public FactAppAddStatDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_add_stat
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public int countByExample(FactAppAddStatExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("fact_app_add_stat.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_add_stat
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public int deleteByExample(FactAppAddStatExample example) throws SQLException {
        int rows = sqlMapClient.delete("fact_app_add_stat.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_add_stat
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public int deleteByPrimaryKey(Long id) throws SQLException {
        FactAppAddStat key = new FactAppAddStat();
        key.setId(id);
        int rows = sqlMapClient.delete("fact_app_add_stat.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_add_stat
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void insert(FactAppAddStat record) throws SQLException {
        sqlMapClient.insert("fact_app_add_stat.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_add_stat
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void insertSelective(FactAppAddStat record) throws SQLException {
        sqlMapClient.insert("fact_app_add_stat.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_add_stat
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public List selectByExample(FactAppAddStatExample example) throws SQLException {
        List list = sqlMapClient.queryForList("fact_app_add_stat.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_add_stat
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public FactAppAddStat selectByPrimaryKey(Long id) throws SQLException {
        FactAppAddStat key = new FactAppAddStat();
        key.setId(id);
        FactAppAddStat record = (FactAppAddStat) sqlMapClient.queryForObject("fact_app_add_stat.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_add_stat
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public int updateByExampleSelective(FactAppAddStat record, FactAppAddStatExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("fact_app_add_stat.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_add_stat
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public int updateByExample(FactAppAddStat record, FactAppAddStatExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("fact_app_add_stat.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_add_stat
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public int updateByPrimaryKeySelective(FactAppAddStat record) throws SQLException {
        int rows = sqlMapClient.update("fact_app_add_stat.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_add_stat
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public int updateByPrimaryKey(FactAppAddStat record) throws SQLException {
        int rows = sqlMapClient.update("fact_app_add_stat.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table fact_app_add_stat
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private static class UpdateByExampleParms extends FactAppAddStatExample {
        private Object record;

        public UpdateByExampleParms(Object record, FactAppAddStatExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}