package com.wangli.data.analysis.ar.adc.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.analysis.ar.adc.module.FactAppStat;
import com.wangli.data.analysis.ar.adc.module.FactAppStatExample;
import java.sql.SQLException;
import java.util.List;

public class FactAppStatDAOImpl implements FactAppStatDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table fact_app_stat
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_stat
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public FactAppStatDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_stat
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public int countByExample(FactAppStatExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("fact_app_stat.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_stat
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public int deleteByExample(FactAppStatExample example) throws SQLException {
        int rows = sqlMapClient.delete("fact_app_stat.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_stat
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public int deleteByPrimaryKey(Long id) throws SQLException {
        FactAppStat key = new FactAppStat();
        key.setId(id);
        int rows = sqlMapClient.delete("fact_app_stat.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_stat
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public void insert(FactAppStat record) throws SQLException {
        sqlMapClient.insert("fact_app_stat.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_stat
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public void insertSelective(FactAppStat record) throws SQLException {
        sqlMapClient.insert("fact_app_stat.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_stat
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public List selectByExample(FactAppStatExample example) throws SQLException {
        List list = sqlMapClient.queryForList("fact_app_stat.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_stat
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public FactAppStat selectByPrimaryKey(Long id) throws SQLException {
        FactAppStat key = new FactAppStat();
        key.setId(id);
        FactAppStat record = (FactAppStat) sqlMapClient.queryForObject("fact_app_stat.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_stat
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public int updateByExampleSelective(FactAppStat record, FactAppStatExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("fact_app_stat.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_stat
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public int updateByExample(FactAppStat record, FactAppStatExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("fact_app_stat.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_stat
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public int updateByPrimaryKeySelective(FactAppStat record) throws SQLException {
        int rows = sqlMapClient.update("fact_app_stat.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table fact_app_stat
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    public int updateByPrimaryKey(FactAppStat record) throws SQLException {
        int rows = sqlMapClient.update("fact_app_stat.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table fact_app_stat
     *
     * @ibatorgenerated Mon Nov 17 10:52:28 CST 2014
     */
    private static class UpdateByExampleParms extends FactAppStatExample {
        private Object record;

        public UpdateByExampleParms(Object record, FactAppStatExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}