package com.wangli.data.analysis.ar.adc.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.analysis.ar.adc.module.InstallAppLog;
import com.wangli.data.analysis.ar.adc.module.InstallAppLogExample;
import java.sql.SQLException;
import java.util.List;

public class InstallAppLogDAOImpl implements InstallAppLogDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public InstallAppLogDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int countByExample(InstallAppLogExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("install_app_log.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int deleteByExample(InstallAppLogExample example) throws SQLException {
        int rows = sqlMapClient.delete("install_app_log.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int deleteByPrimaryKey(Long id) throws SQLException {
        InstallAppLog key = new InstallAppLog();
        key.setId(id);
        int rows = sqlMapClient.delete("install_app_log.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void insert(InstallAppLog record) throws SQLException {
        sqlMapClient.insert("install_app_log.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void insertSelective(InstallAppLog record) throws SQLException {
        sqlMapClient.insert("install_app_log.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public List selectByExampleWithBLOBs(InstallAppLogExample example) throws SQLException {
        List list = sqlMapClient.queryForList("install_app_log.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }
    
    public List selectByExampleWithBLOBs(InstallAppLogExample example,int beginInex,int length) throws SQLException {
    	List list = sqlMapClient.queryForList("install_app_log.ibatorgenerated_selectByExampleWithBLOBs", example,beginInex,length);
    	return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public List selectByExampleWithoutBLOBs(InstallAppLogExample example) throws SQLException {
        List list = sqlMapClient.queryForList("install_app_log.ibatorgenerated_selectByExample", example);
        return list;
    }
    
    public List selectByExampleWithoutBLOBs(InstallAppLogExample example,int beginInex,int length) throws SQLException {
    	List list = sqlMapClient.queryForList("install_app_log.ibatorgenerated_selectByExample", example,beginInex,length);
    	return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public InstallAppLog selectByPrimaryKey(Long id) throws SQLException {
        InstallAppLog key = new InstallAppLog();
        key.setId(id);
        InstallAppLog record = (InstallAppLog) sqlMapClient.queryForObject("install_app_log.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByExampleSelective(InstallAppLog record, InstallAppLogExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("install_app_log.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByExampleWithBLOBs(InstallAppLog record, InstallAppLogExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("install_app_log.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByExampleWithoutBLOBs(InstallAppLog record, InstallAppLogExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("install_app_log.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByPrimaryKeySelective(InstallAppLog record) throws SQLException {
        int rows = sqlMapClient.update("install_app_log.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByPrimaryKeyWithBLOBs(InstallAppLog record) throws SQLException {
        int rows = sqlMapClient.update("install_app_log.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public int updateByPrimaryKeyWithoutBLOBs(InstallAppLog record) throws SQLException {
        int rows = sqlMapClient.update("install_app_log.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private static class UpdateByExampleParms extends InstallAppLogExample {
        private Object record;

        public UpdateByExampleParms(Object record, InstallAppLogExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}