package com.wangli.data.analysis.ar.adc.dao;

import com.wangli.data.analysis.ar.adc.module.InstallAppLog;
import com.wangli.data.analysis.ar.adc.module.InstallAppLogExample;
import java.sql.SQLException;
import java.util.List;

public interface InstallAppLogDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int countByExample(InstallAppLogExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int deleteByExample(InstallAppLogExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int deleteByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    void insert(InstallAppLog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    void insertSelective(InstallAppLog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    List selectByExampleWithBLOBs(InstallAppLogExample example) throws SQLException;
    List selectByExampleWithBLOBs(InstallAppLogExample example,int beginInex,int length) throws SQLException;

    
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    List selectByExampleWithoutBLOBs(InstallAppLogExample example) throws SQLException;
    List selectByExampleWithoutBLOBs(InstallAppLogExample example,int beginInex,int length) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    InstallAppLog selectByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByExampleSelective(InstallAppLog record, InstallAppLogExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByExampleWithBLOBs(InstallAppLog record, InstallAppLogExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByExampleWithoutBLOBs(InstallAppLog record, InstallAppLogExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByPrimaryKeySelective(InstallAppLog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(InstallAppLog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    int updateByPrimaryKeyWithoutBLOBs(InstallAppLog record) throws SQLException;
}