package com.wangli.data.etl.report.gfanmarket.dao;

import java.sql.SQLException;
import java.util.List;

import com.wangli.data.etl.report.gfanmarket.module.ClientEventLog;
import com.wangli.data.etl.report.gfanmarket.module.ClientEventLogExample;

public interface ClientEventLogDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    int countByExample(ClientEventLogExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    int deleteByExample(ClientEventLogExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    int deleteByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    void insert(ClientEventLog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    void insertSelective(ClientEventLog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    List selectByExampleWithBLOBs(ClientEventLogExample example) throws SQLException;
    List selectByExampleWithBLOBs(ClientEventLogExample example,int beginInex,int length) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    List selectByExampleWithoutBLOBs(ClientEventLogExample example) throws SQLException;
    List selectByExampleWithoutBLOBs(ClientEventLogExample example,int beginInex,int length) throws SQLException;
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    ClientEventLog selectByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    int updateByExampleSelective(ClientEventLog record, ClientEventLogExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    int updateByExampleWithBLOBs(ClientEventLog record, ClientEventLogExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    int updateByExampleWithoutBLOBs(ClientEventLog record, ClientEventLogExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    int updateByPrimaryKeySelective(ClientEventLog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(ClientEventLog record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    int updateByPrimaryKeyWithoutBLOBs(ClientEventLog record) throws SQLException;
}