package com.wangli.data.etl.report.gfanmarket.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.etl.report.gfanmarket.module.ClientEventLog;
import com.wangli.data.etl.report.gfanmarket.module.ClientEventLogExample;

public class ClientEventLogDAOImpl implements ClientEventLogDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public ClientEventLogDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public int countByExample(ClientEventLogExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("client_event_log.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public int deleteByExample(ClientEventLogExample example) throws SQLException {
        int rows = sqlMapClient.delete("client_event_log.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public int deleteByPrimaryKey(Long id) throws SQLException {
        ClientEventLog key = new ClientEventLog();
        key.setId(id);
        int rows = sqlMapClient.delete("client_event_log.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void insert(ClientEventLog record) throws SQLException {
        sqlMapClient.insert("client_event_log.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void insertSelective(ClientEventLog record) throws SQLException {
        sqlMapClient.insert("client_event_log.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public List selectByExampleWithBLOBs(ClientEventLogExample example) throws SQLException {
        List list = sqlMapClient.queryForList("client_event_log.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public List selectByExampleWithoutBLOBs(ClientEventLogExample example) throws SQLException {
        List list = sqlMapClient.queryForList("client_event_log.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public ClientEventLog selectByPrimaryKey(Long id) throws SQLException {
        ClientEventLog key = new ClientEventLog();
        key.setId(id);
        ClientEventLog record = (ClientEventLog) sqlMapClient.queryForObject("client_event_log.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public int updateByExampleSelective(ClientEventLog record, ClientEventLogExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("client_event_log.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public int updateByExampleWithBLOBs(ClientEventLog record, ClientEventLogExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("client_event_log.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public int updateByExampleWithoutBLOBs(ClientEventLog record, ClientEventLogExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("client_event_log.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public int updateByPrimaryKeySelective(ClientEventLog record) throws SQLException {
        int rows = sqlMapClient.update("client_event_log.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public int updateByPrimaryKeyWithBLOBs(ClientEventLog record) throws SQLException {
        int rows = sqlMapClient.update("client_event_log.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public int updateByPrimaryKeyWithoutBLOBs(ClientEventLog record) throws SQLException {
        int rows = sqlMapClient.update("client_event_log.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private static class UpdateByExampleParms extends ClientEventLogExample {
        private Object record;

        public UpdateByExampleParms(Object record, ClientEventLogExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List selectByExampleWithoutBLOBs(ClientEventLogExample example,
			int beginInex, int length) throws SQLException {
		List list = sqlMapClient.queryForList("client_event_log.ibatorgenerated_selectByExample", example,beginInex,length);
    	return list;
	}

	@Override
	public List selectByExampleWithBLOBs(ClientEventLogExample example,
			int beginInex, int length) throws SQLException {
		 List list = sqlMapClient.queryForList("client_event_log.ibatorgenerated_selectByExampleWithBLOBs", example,beginInex,length);
	     return list;
	}
}