package com.wangli.data.etl.report.gfanmarket.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.etl.report.gfanmarket.module.GfanCfgContent;
import com.wangli.data.etl.report.gfanmarket.module.GfanCfgContentExample;
import java.sql.SQLException;
import java.util.List;

public class GfanCfgContentDAOImpl implements GfanCfgContentDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table gfan_cfg_content
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public GfanCfgContentDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public int countByExample(GfanCfgContentExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("gfan_cfg_content.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public int deleteByExample(GfanCfgContentExample example) throws SQLException {
        int rows = sqlMapClient.delete("gfan_cfg_content.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        GfanCfgContent key = new GfanCfgContent();
        key.setId(id);
        int rows = sqlMapClient.delete("gfan_cfg_content.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public void insert(GfanCfgContent record) throws SQLException {
        sqlMapClient.insert("gfan_cfg_content.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public void insertSelective(GfanCfgContent record) throws SQLException {
        sqlMapClient.insert("gfan_cfg_content.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public List selectByExample(GfanCfgContentExample example) throws SQLException {
        List list = sqlMapClient.queryForList("gfan_cfg_content.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public GfanCfgContent selectByPrimaryKey(Integer id) throws SQLException {
        GfanCfgContent key = new GfanCfgContent();
        key.setId(id);
        GfanCfgContent record = (GfanCfgContent) sqlMapClient.queryForObject("gfan_cfg_content.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public int updateByExampleSelective(GfanCfgContent record, GfanCfgContentExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("gfan_cfg_content.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public int updateByExample(GfanCfgContent record, GfanCfgContentExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("gfan_cfg_content.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public int updateByPrimaryKeySelective(GfanCfgContent record) throws SQLException {
        int rows = sqlMapClient.update("gfan_cfg_content.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public int updateByPrimaryKey(GfanCfgContent record) throws SQLException {
        int rows = sqlMapClient.update("gfan_cfg_content.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table gfan_cfg_content
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    private static class UpdateByExampleParms extends GfanCfgContentExample {
        private Object record;

        public UpdateByExampleParms(Object record, GfanCfgContentExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}