package com.wangli.data.etl.report.gfanmarket.dao;

import com.wangli.data.etl.report.gfanmarket.module.GfanCfgContentGroup;
import com.wangli.data.etl.report.gfanmarket.module.GfanCfgContentGroupExample;
import java.sql.SQLException;
import java.util.List;

public interface GfanCfgContentGroupDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    int countByExample(GfanCfgContentGroupExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    int deleteByExample(GfanCfgContentGroupExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    void insert(GfanCfgContentGroup record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    void insertSelective(GfanCfgContentGroup record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    List selectByExample(GfanCfgContentGroupExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    GfanCfgContentGroup selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    int updateByExampleSelective(GfanCfgContentGroup record, GfanCfgContentGroupExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    int updateByExample(GfanCfgContentGroup record, GfanCfgContentGroupExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    int updateByPrimaryKeySelective(GfanCfgContentGroup record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    int updateByPrimaryKey(GfanCfgContentGroup record) throws SQLException;
}