package com.wangli.data.etl.report.gfanmarket.dao;

import com.wangli.data.etl.report.gfanmarket.module.GfanCfgRankProduct;
import com.wangli.data.etl.report.gfanmarket.module.GfanCfgRankProductExample;
import java.sql.SQLException;
import java.util.List;

public interface GfanCfgRankProductDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    int countByExample(GfanCfgRankProductExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    int deleteByExample(GfanCfgRankProductExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    void insert(GfanCfgRankProduct record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    void insertSelective(GfanCfgRankProduct record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    List selectByExample(GfanCfgRankProductExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    GfanCfgRankProduct selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    int updateByExampleSelective(GfanCfgRankProduct record, GfanCfgRankProductExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    int updateByExample(GfanCfgRankProduct record, GfanCfgRankProductExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    int updateByPrimaryKeySelective(GfanCfgRankProduct record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    int updateByPrimaryKey(GfanCfgRankProduct record) throws SQLException;
}