package com.wangli.data.etl.report.gfanmarket.dao;

import com.wangli.data.etl.report.gfanmarket.module.GfanClientEventClick;
import com.wangli.data.etl.report.gfanmarket.module.GfanClientEventClickExample;
import java.sql.SQLException;
import java.util.List;

public interface GfanClientEventClickDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    int countByExample(GfanClientEventClickExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    int deleteByExample(GfanClientEventClickExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    int deleteByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    void insert(GfanClientEventClick record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    void insertSelective(GfanClientEventClick record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    List selectByExampleWithBLOBs(GfanClientEventClickExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    List selectByExampleWithoutBLOBs(GfanClientEventClickExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    GfanClientEventClick selectByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    int updateByExampleSelective(GfanClientEventClick record, GfanClientEventClickExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    int updateByExampleWithBLOBs(GfanClientEventClick record, GfanClientEventClickExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    int updateByExampleWithoutBLOBs(GfanClientEventClick record, GfanClientEventClickExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    int updateByPrimaryKeySelective(GfanClientEventClick record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(GfanClientEventClick record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    int updateByPrimaryKeyWithoutBLOBs(GfanClientEventClick record) throws SQLException;
}