package com.wangli.data.etl.report.gfanmarket.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.etl.report.gfanmarket.module.GfanCfgContentGroup;
import com.wangli.data.etl.report.gfanmarket.module.GfanCfgContentGroupExample;
import java.sql.SQLException;
import java.util.List;

public class GfanCfgContentGroupDAOImpl implements GfanCfgContentGroupDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public GfanCfgContentGroupDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public int countByExample(GfanCfgContentGroupExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("gfan_cfg_content_group.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public int deleteByExample(GfanCfgContentGroupExample example) throws SQLException {
        int rows = sqlMapClient.delete("gfan_cfg_content_group.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        GfanCfgContentGroup key = new GfanCfgContentGroup();
        key.setId(id);
        int rows = sqlMapClient.delete("gfan_cfg_content_group.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public void insert(GfanCfgContentGroup record) throws SQLException {
        sqlMapClient.insert("gfan_cfg_content_group.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public void insertSelective(GfanCfgContentGroup record) throws SQLException {
        sqlMapClient.insert("gfan_cfg_content_group.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public List selectByExample(GfanCfgContentGroupExample example) throws SQLException {
        List list = sqlMapClient.queryForList("gfan_cfg_content_group.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public GfanCfgContentGroup selectByPrimaryKey(Integer id) throws SQLException {
        GfanCfgContentGroup key = new GfanCfgContentGroup();
        key.setId(id);
        GfanCfgContentGroup record = (GfanCfgContentGroup) sqlMapClient.queryForObject("gfan_cfg_content_group.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public int updateByExampleSelective(GfanCfgContentGroup record, GfanCfgContentGroupExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("gfan_cfg_content_group.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public int updateByExample(GfanCfgContentGroup record, GfanCfgContentGroupExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("gfan_cfg_content_group.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public int updateByPrimaryKeySelective(GfanCfgContentGroup record) throws SQLException {
        int rows = sqlMapClient.update("gfan_cfg_content_group.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    public int updateByPrimaryKey(GfanCfgContentGroup record) throws SQLException {
        int rows = sqlMapClient.update("gfan_cfg_content_group.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table gfan_cfg_content_group
     *
     * @ibatorgenerated Tue Dec 09 16:44:18 CST 2014
     */
    private static class UpdateByExampleParms extends GfanCfgContentGroupExample {
        private Object record;

        public UpdateByExampleParms(Object record, GfanCfgContentGroupExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}