package com.wangli.data.etl.report.gfanmarket.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.etl.report.gfanmarket.module.GfanClientEventClick;
import com.wangli.data.etl.report.gfanmarket.module.GfanClientEventClickExample;
import java.sql.SQLException;
import java.util.List;

public class GfanClientEventClickDAOImpl implements GfanClientEventClickDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public GfanClientEventClickDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public int countByExample(GfanClientEventClickExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("gfan_client_event_click.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public int deleteByExample(GfanClientEventClickExample example) throws SQLException {
        int rows = sqlMapClient.delete("gfan_client_event_click.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public int deleteByPrimaryKey(Long id) throws SQLException {
        GfanClientEventClick key = new GfanClientEventClick();
        key.setId(id);
        int rows = sqlMapClient.delete("gfan_client_event_click.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void insert(GfanClientEventClick record) throws SQLException {
        sqlMapClient.insert("gfan_client_event_click.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void insertSelective(GfanClientEventClick record) throws SQLException {
        sqlMapClient.insert("gfan_client_event_click.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public List selectByExampleWithBLOBs(GfanClientEventClickExample example) throws SQLException {
        List list = sqlMapClient.queryForList("gfan_client_event_click.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public List selectByExampleWithoutBLOBs(GfanClientEventClickExample example) throws SQLException {
        List list = sqlMapClient.queryForList("gfan_client_event_click.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public GfanClientEventClick selectByPrimaryKey(Long id) throws SQLException {
        GfanClientEventClick key = new GfanClientEventClick();
        key.setId(id);
        GfanClientEventClick record = (GfanClientEventClick) sqlMapClient.queryForObject("gfan_client_event_click.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public int updateByExampleSelective(GfanClientEventClick record, GfanClientEventClickExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("gfan_client_event_click.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public int updateByExampleWithBLOBs(GfanClientEventClick record, GfanClientEventClickExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("gfan_client_event_click.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public int updateByExampleWithoutBLOBs(GfanClientEventClick record, GfanClientEventClickExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("gfan_client_event_click.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public int updateByPrimaryKeySelective(GfanClientEventClick record) throws SQLException {
        int rows = sqlMapClient.update("gfan_client_event_click.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public int updateByPrimaryKeyWithBLOBs(GfanClientEventClick record) throws SQLException {
        int rows = sqlMapClient.update("gfan_client_event_click.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public int updateByPrimaryKeyWithoutBLOBs(GfanClientEventClick record) throws SQLException {
        int rows = sqlMapClient.update("gfan_client_event_click.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table gfan_client_event_click
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private static class UpdateByExampleParms extends GfanClientEventClickExample {
        private Object record;

        public UpdateByExampleParms(Object record, GfanClientEventClickExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}