package com.wangli.data.etl.report.gfanmarket.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.etl.report.gfanmarket.module.GfanClientEventDownload;
import com.wangli.data.etl.report.gfanmarket.module.GfanClientEventDownloadExample;
import java.sql.SQLException;
import java.util.List;

public class GfanClientEventDownloadDAOImpl implements GfanClientEventDownloadDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	public GfanClientEventDownloadDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	public int countByExample(GfanClientEventDownloadExample example)
			throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"gfan_client_event_download.ibatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	public int deleteByExample(GfanClientEventDownloadExample example)
			throws SQLException {
		int rows = sqlMapClient.delete(
				"gfan_client_event_download.ibatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	public int deleteByPrimaryKey(Long id) throws SQLException {
		GfanClientEventDownload key = new GfanClientEventDownload();
		key.setId(id);
		int rows = sqlMapClient
				.delete("gfan_client_event_download.ibatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	public void insert(GfanClientEventDownload record) throws SQLException {
		sqlMapClient.insert(
				"gfan_client_event_download.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	public void insertSelective(GfanClientEventDownload record)
			throws SQLException {
		sqlMapClient.insert(
				"gfan_client_event_download.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	public List selectByExampleWithBLOBs(GfanClientEventDownloadExample example)
			throws SQLException {
		List list = sqlMapClient
				.queryForList(
						"gfan_client_event_download.ibatorgenerated_selectByExampleWithBLOBs",
						example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	public List selectByExampleWithoutBLOBs(
			GfanClientEventDownloadExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"gfan_client_event_download.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	public GfanClientEventDownload selectByPrimaryKey(Long id)
			throws SQLException {
		GfanClientEventDownload key = new GfanClientEventDownload();
		key.setId(id);
		GfanClientEventDownload record = (GfanClientEventDownload) sqlMapClient
				.queryForObject(
						"gfan_client_event_download.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	public int updateByExampleSelective(GfanClientEventDownload record,
			GfanClientEventDownloadExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient
				.update("gfan_client_event_download.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	public int updateByExampleWithBLOBs(GfanClientEventDownload record,
			GfanClientEventDownloadExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient
				.update("gfan_client_event_download.ibatorgenerated_updateByExampleWithBLOBs",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	public int updateByExampleWithoutBLOBs(GfanClientEventDownload record,
			GfanClientEventDownloadExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"gfan_client_event_download.ibatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	public int updateByPrimaryKeySelective(GfanClientEventDownload record)
			throws SQLException {
		int rows = sqlMapClient
				.update("gfan_client_event_download.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	public int updateByPrimaryKeyWithBLOBs(GfanClientEventDownload record)
			throws SQLException {
		int rows = sqlMapClient
				.update("gfan_client_event_download.ibatorgenerated_updateByPrimaryKeyWithBLOBs",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	public int updateByPrimaryKeyWithoutBLOBs(GfanClientEventDownload record)
			throws SQLException {
		int rows = sqlMapClient
				.update("gfan_client_event_download.ibatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table gfan_client_event_download
	 * @ibatorgenerated  Fri Nov 28 11:18:55 CST 2014
	 */
	private static class UpdateByExampleParms extends
			GfanClientEventDownloadExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				GfanClientEventDownloadExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}