package com.wangli.data.etl.report.gfanmarket.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.etl.report.gfanmarket.module.GfanClientEventBannerclick;
import com.wangli.data.etl.report.gfanmarket.module.GfanClientEventBannerclickExample;
import java.sql.SQLException;
import java.util.List;

public class GfanClientEventBannerclickDAOImpl implements GfanClientEventBannerclickDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public GfanClientEventBannerclickDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public int countByExample(GfanClientEventBannerclickExample example)
			throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"gfan_client_event_bannerclick.ibatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public int deleteByExample(GfanClientEventBannerclickExample example)
			throws SQLException {
		int rows = sqlMapClient
				.delete("gfan_client_event_bannerclick.ibatorgenerated_deleteByExample",
						example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public int deleteByPrimaryKey(Long id) throws SQLException {
		GfanClientEventBannerclick key = new GfanClientEventBannerclick();
		key.setId(id);
		int rows = sqlMapClient
				.delete("gfan_client_event_bannerclick.ibatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void insert(GfanClientEventBannerclick record) throws SQLException {
		sqlMapClient.insert(
				"gfan_client_event_bannerclick.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void insertSelective(GfanClientEventBannerclick record)
			throws SQLException {
		sqlMapClient
				.insert("gfan_client_event_bannerclick.ibatorgenerated_insertSelective",
						record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public List selectByExampleWithBLOBs(
			GfanClientEventBannerclickExample example) throws SQLException {
		List list = sqlMapClient
				.queryForList(
						"gfan_client_event_bannerclick.ibatorgenerated_selectByExampleWithBLOBs",
						example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public List selectByExampleWithoutBLOBs(
			GfanClientEventBannerclickExample example) throws SQLException {
		List list = sqlMapClient
				.queryForList(
						"gfan_client_event_bannerclick.ibatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public GfanClientEventBannerclick selectByPrimaryKey(Long id)
			throws SQLException {
		GfanClientEventBannerclick key = new GfanClientEventBannerclick();
		key.setId(id);
		GfanClientEventBannerclick record = (GfanClientEventBannerclick) sqlMapClient
				.queryForObject(
						"gfan_client_event_bannerclick.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public int updateByExampleSelective(GfanClientEventBannerclick record,
			GfanClientEventBannerclickExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient
				.update("gfan_client_event_bannerclick.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public int updateByExampleWithBLOBs(GfanClientEventBannerclick record,
			GfanClientEventBannerclickExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient
				.update("gfan_client_event_bannerclick.ibatorgenerated_updateByExampleWithBLOBs",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public int updateByExampleWithoutBLOBs(GfanClientEventBannerclick record,
			GfanClientEventBannerclickExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient
				.update("gfan_client_event_bannerclick.ibatorgenerated_updateByExample",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public int updateByPrimaryKeySelective(GfanClientEventBannerclick record)
			throws SQLException {
		int rows = sqlMapClient
				.update("gfan_client_event_bannerclick.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public int updateByPrimaryKeyWithBLOBs(GfanClientEventBannerclick record)
			throws SQLException {
		int rows = sqlMapClient
				.update("gfan_client_event_bannerclick.ibatorgenerated_updateByPrimaryKeyWithBLOBs",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public int updateByPrimaryKeyWithoutBLOBs(GfanClientEventBannerclick record)
			throws SQLException {
		int rows = sqlMapClient
				.update("gfan_client_event_bannerclick.ibatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table gfan_client_event_bannerclick
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private static class UpdateByExampleParms extends
			GfanClientEventBannerclickExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				GfanClientEventBannerclickExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}