package com.wangli.data.etl.report.gfanmarket.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.etl.report.gfanmarket.module.GfanCfgRankProduct;
import com.wangli.data.etl.report.gfanmarket.module.GfanCfgRankProductExample;
import java.sql.SQLException;
import java.util.List;

public class GfanCfgRankProductDAOImpl implements GfanCfgRankProductDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    public GfanCfgRankProductDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    public int countByExample(GfanCfgRankProductExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("gfan_cfg_rank_product.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    public int deleteByExample(GfanCfgRankProductExample example) throws SQLException {
        int rows = sqlMapClient.delete("gfan_cfg_rank_product.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        GfanCfgRankProduct key = new GfanCfgRankProduct();
        key.setId(id);
        int rows = sqlMapClient.delete("gfan_cfg_rank_product.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    public void insert(GfanCfgRankProduct record) throws SQLException {
        sqlMapClient.insert("gfan_cfg_rank_product.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    public void insertSelective(GfanCfgRankProduct record) throws SQLException {
        sqlMapClient.insert("gfan_cfg_rank_product.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    public List selectByExample(GfanCfgRankProductExample example) throws SQLException {
        List list = sqlMapClient.queryForList("gfan_cfg_rank_product.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    public GfanCfgRankProduct selectByPrimaryKey(Integer id) throws SQLException {
        GfanCfgRankProduct key = new GfanCfgRankProduct();
        key.setId(id);
        GfanCfgRankProduct record = (GfanCfgRankProduct) sqlMapClient.queryForObject("gfan_cfg_rank_product.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    public int updateByExampleSelective(GfanCfgRankProduct record, GfanCfgRankProductExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("gfan_cfg_rank_product.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    public int updateByExample(GfanCfgRankProduct record, GfanCfgRankProductExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("gfan_cfg_rank_product.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    public int updateByPrimaryKeySelective(GfanCfgRankProduct record) throws SQLException {
        int rows = sqlMapClient.update("gfan_cfg_rank_product.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    public int updateByPrimaryKey(GfanCfgRankProduct record) throws SQLException {
        int rows = sqlMapClient.update("gfan_cfg_rank_product.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table gfan_cfg_rank_product
     *
     * @ibatorgenerated Mon Nov 24 17:55:55 CST 2014
     */
    private static class UpdateByExampleParms extends GfanCfgRankProductExample {
        private Object record;

        public UpdateByExampleParms(Object record, GfanCfgRankProductExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}