package com.wangli.data.etl.report.gfanmarket.dao;

import com.wangli.data.etl.report.gfanmarket.module.SearchHotwordsLog;
import com.wangli.data.etl.report.gfanmarket.module.SearchHotwordsLogExample;
import java.sql.SQLException;
import java.util.List;

public interface SearchHotwordsLogDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_hotwords_log
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	int countByExample(SearchHotwordsLogExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_hotwords_log
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	int deleteByExample(SearchHotwordsLogExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_hotwords_log
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	void insert(SearchHotwordsLog record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_hotwords_log
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	void insertSelective(SearchHotwordsLog record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_hotwords_log
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	List selectByExample(SearchHotwordsLogExample example) throws SQLException;
	
	List selectHotWordsReplaceByExample(SearchHotwordsLogExample example) throws SQLException;
	
	List selectHotWordsAllByExample(SearchHotwordsLogExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_hotwords_log
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	int updateByExampleSelective(SearchHotwordsLog record,
			SearchHotwordsLogExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_hotwords_log
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	int updateByExample(SearchHotwordsLog record,
			SearchHotwordsLogExample example) throws SQLException;
}