package com.wangli.data.etl.report.gfanmarket.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.wangli.data.etl.report.gfanmarket.module.StatVersion;
import com.wangli.data.etl.report.gfanmarket.module.StatVersionExample;
import java.sql.SQLException;
import java.util.List;

public class StatVersionDAOImpl implements StatVersionDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	public StatVersionDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	public int countByExample(StatVersionExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"stat_version.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	public int deleteByExample(StatVersionExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"stat_version.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		StatVersion key = new StatVersion();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"stat_version.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	public void insert(StatVersion record) throws SQLException {
		sqlMapClient.insert("stat_version.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	public void insertSelective(StatVersion record) throws SQLException {
		sqlMapClient.insert("stat_version.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	public List selectByExample(StatVersionExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"stat_version.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	public StatVersion selectByPrimaryKey(Integer id) throws SQLException {
		StatVersion key = new StatVersion();
		key.setId(id);
		StatVersion record = (StatVersion) sqlMapClient.queryForObject(
				"stat_version.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	public int updateByExampleSelective(StatVersion record,
			StatVersionExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"stat_version.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	public int updateByExample(StatVersion record, StatVersionExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"stat_version.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	public int updateByPrimaryKeySelective(StatVersion record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"stat_version.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	public int updateByPrimaryKey(StatVersion record) throws SQLException {
		int rows = sqlMapClient.update(
				"stat_version.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	private static class UpdateByExampleParms extends StatVersionExample {
		private Object record;

		public UpdateByExampleParms(Object record, StatVersionExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}