package com.wangli.data.etl.report.gfanmarket.dao;

import com.wangli.data.etl.report.gfanmarket.module.StatVersion;
import com.wangli.data.etl.report.gfanmarket.module.StatVersionExample;
import java.sql.SQLException;
import java.util.List;

public interface StatVersionDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	int countByExample(StatVersionExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	int deleteByExample(StatVersionExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	void insert(StatVersion record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	void insertSelective(StatVersion record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	List selectByExample(StatVersionExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	StatVersion selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	int updateByExampleSelective(StatVersion record, StatVersionExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	int updateByExample(StatVersion record, StatVersionExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	int updateByPrimaryKeySelective(StatVersion record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table stat_version
	 * @ibatorgenerated  Mon Nov 24 17:55:55 CST 2014
	 */
	int updateByPrimaryKey(StatVersion record) throws SQLException;
}