package com.wangli.data.etl.report.gfanmarket.module;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ClientEventLogExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public ClientEventLogExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    protected ClientEventLogExample(ClientEventLogExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table client_event_log
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andDataTimeIsNull() {
            addCriterion("data_time is null");
            return this;
        }

        public Criteria andDataTimeIsNotNull() {
            addCriterion("data_time is not null");
            return this;
        }

        public Criteria andDataTimeEqualTo(String value) {
            addCriterion("data_time =", value, "dataTime");
            return this;
        }

        public Criteria andDataTimeNotEqualTo(String value) {
            addCriterion("data_time <>", value, "dataTime");
            return this;
        }

        public Criteria andDataTimeGreaterThan(String value) {
            addCriterion("data_time >", value, "dataTime");
            return this;
        }

        public Criteria andDataTimeGreaterThanOrEqualTo(String value) {
            addCriterion("data_time >=", value, "dataTime");
            return this;
        }

        public Criteria andDataTimeLessThan(String value) {
            addCriterion("data_time <", value, "dataTime");
            return this;
        }

        public Criteria andDataTimeLessThanOrEqualTo(String value) {
            addCriterion("data_time <=", value, "dataTime");
            return this;
        }

        public Criteria andDataTimeLike(String value) {
            addCriterion("data_time like", value, "dataTime");
            return this;
        }

        public Criteria andDataTimeNotLike(String value) {
            addCriterion("data_time not like", value, "dataTime");
            return this;
        }

        public Criteria andDataTimeIn(List values) {
            addCriterion("data_time in", values, "dataTime");
            return this;
        }

        public Criteria andDataTimeNotIn(List values) {
            addCriterion("data_time not in", values, "dataTime");
            return this;
        }

        public Criteria andDataTimeBetween(String value1, String value2) {
            addCriterion("data_time between", value1, value2, "dataTime");
            return this;
        }

        public Criteria andDataTimeNotBetween(String value1, String value2) {
            addCriterion("data_time not between", value1, value2, "dataTime");
            return this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return this;
        }

        public Criteria andVersionIn(List values) {
            addCriterion("version in", values, "version");
            return this;
        }

        public Criteria andVersionNotIn(List values) {
            addCriterion("version not in", values, "version");
            return this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return this;
        }

        public Criteria andMethodIsNull() {
            addCriterion("method is null");
            return this;
        }

        public Criteria andMethodIsNotNull() {
            addCriterion("method is not null");
            return this;
        }

        public Criteria andMethodEqualTo(String value) {
            addCriterion("method =", value, "method");
            return this;
        }

        public Criteria andMethodNotEqualTo(String value) {
            addCriterion("method <>", value, "method");
            return this;
        }

        public Criteria andMethodGreaterThan(String value) {
            addCriterion("method >", value, "method");
            return this;
        }

        public Criteria andMethodGreaterThanOrEqualTo(String value) {
            addCriterion("method >=", value, "method");
            return this;
        }

        public Criteria andMethodLessThan(String value) {
            addCriterion("method <", value, "method");
            return this;
        }

        public Criteria andMethodLessThanOrEqualTo(String value) {
            addCriterion("method <=", value, "method");
            return this;
        }

        public Criteria andMethodLike(String value) {
            addCriterion("method like", value, "method");
            return this;
        }

        public Criteria andMethodNotLike(String value) {
            addCriterion("method not like", value, "method");
            return this;
        }

        public Criteria andMethodIn(List values) {
            addCriterion("method in", values, "method");
            return this;
        }

        public Criteria andMethodNotIn(List values) {
            addCriterion("method not in", values, "method");
            return this;
        }

        public Criteria andMethodBetween(String value1, String value2) {
            addCriterion("method between", value1, value2, "method");
            return this;
        }

        public Criteria andMethodNotBetween(String value1, String value2) {
            addCriterion("method not between", value1, value2, "method");
            return this;
        }

        public Criteria andPlatformIsNull() {
            addCriterion("platform is null");
            return this;
        }

        public Criteria andPlatformIsNotNull() {
            addCriterion("platform is not null");
            return this;
        }

        public Criteria andPlatformEqualTo(String value) {
            addCriterion("platform =", value, "platform");
            return this;
        }

        public Criteria andPlatformNotEqualTo(String value) {
            addCriterion("platform <>", value, "platform");
            return this;
        }

        public Criteria andPlatformGreaterThan(String value) {
            addCriterion("platform >", value, "platform");
            return this;
        }

        public Criteria andPlatformGreaterThanOrEqualTo(String value) {
            addCriterion("platform >=", value, "platform");
            return this;
        }

        public Criteria andPlatformLessThan(String value) {
            addCriterion("platform <", value, "platform");
            return this;
        }

        public Criteria andPlatformLessThanOrEqualTo(String value) {
            addCriterion("platform <=", value, "platform");
            return this;
        }

        public Criteria andPlatformLike(String value) {
            addCriterion("platform like", value, "platform");
            return this;
        }

        public Criteria andPlatformNotLike(String value) {
            addCriterion("platform not like", value, "platform");
            return this;
        }

        public Criteria andPlatformIn(List values) {
            addCriterion("platform in", values, "platform");
            return this;
        }

        public Criteria andPlatformNotIn(List values) {
            addCriterion("platform not in", values, "platform");
            return this;
        }

        public Criteria andPlatformBetween(String value1, String value2) {
            addCriterion("platform between", value1, value2, "platform");
            return this;
        }

        public Criteria andPlatformNotBetween(String value1, String value2) {
            addCriterion("platform not between", value1, value2, "platform");
            return this;
        }

        public Criteria andScreenSizeIsNull() {
            addCriterion("screen_size is null");
            return this;
        }

        public Criteria andScreenSizeIsNotNull() {
            addCriterion("screen_size is not null");
            return this;
        }

        public Criteria andScreenSizeEqualTo(String value) {
            addCriterion("screen_size =", value, "screenSize");
            return this;
        }

        public Criteria andScreenSizeNotEqualTo(String value) {
            addCriterion("screen_size <>", value, "screenSize");
            return this;
        }

        public Criteria andScreenSizeGreaterThan(String value) {
            addCriterion("screen_size >", value, "screenSize");
            return this;
        }

        public Criteria andScreenSizeGreaterThanOrEqualTo(String value) {
            addCriterion("screen_size >=", value, "screenSize");
            return this;
        }

        public Criteria andScreenSizeLessThan(String value) {
            addCriterion("screen_size <", value, "screenSize");
            return this;
        }

        public Criteria andScreenSizeLessThanOrEqualTo(String value) {
            addCriterion("screen_size <=", value, "screenSize");
            return this;
        }

        public Criteria andScreenSizeLike(String value) {
            addCriterion("screen_size like", value, "screenSize");
            return this;
        }

        public Criteria andScreenSizeNotLike(String value) {
            addCriterion("screen_size not like", value, "screenSize");
            return this;
        }

        public Criteria andScreenSizeIn(List values) {
            addCriterion("screen_size in", values, "screenSize");
            return this;
        }

        public Criteria andScreenSizeNotIn(List values) {
            addCriterion("screen_size not in", values, "screenSize");
            return this;
        }

        public Criteria andScreenSizeBetween(String value1, String value2) {
            addCriterion("screen_size between", value1, value2, "screenSize");
            return this;
        }

        public Criteria andScreenSizeNotBetween(String value1, String value2) {
            addCriterion("screen_size not between", value1, value2, "screenSize");
            return this;
        }

        public Criteria andMatchTypeIsNull() {
            addCriterion("match_type is null");
            return this;
        }

        public Criteria andMatchTypeIsNotNull() {
            addCriterion("match_type is not null");
            return this;
        }

        public Criteria andMatchTypeEqualTo(String value) {
            addCriterion("match_type =", value, "matchType");
            return this;
        }

        public Criteria andMatchTypeNotEqualTo(String value) {
            addCriterion("match_type <>", value, "matchType");
            return this;
        }

        public Criteria andMatchTypeGreaterThan(String value) {
            addCriterion("match_type >", value, "matchType");
            return this;
        }

        public Criteria andMatchTypeGreaterThanOrEqualTo(String value) {
            addCriterion("match_type >=", value, "matchType");
            return this;
        }

        public Criteria andMatchTypeLessThan(String value) {
            addCriterion("match_type <", value, "matchType");
            return this;
        }

        public Criteria andMatchTypeLessThanOrEqualTo(String value) {
            addCriterion("match_type <=", value, "matchType");
            return this;
        }

        public Criteria andMatchTypeLike(String value) {
            addCriterion("match_type like", value, "matchType");
            return this;
        }

        public Criteria andMatchTypeNotLike(String value) {
            addCriterion("match_type not like", value, "matchType");
            return this;
        }

        public Criteria andMatchTypeIn(List values) {
            addCriterion("match_type in", values, "matchType");
            return this;
        }

        public Criteria andMatchTypeNotIn(List values) {
            addCriterion("match_type not in", values, "matchType");
            return this;
        }

        public Criteria andMatchTypeBetween(String value1, String value2) {
            addCriterion("match_type between", value1, value2, "matchType");
            return this;
        }

        public Criteria andMatchTypeNotBetween(String value1, String value2) {
            addCriterion("match_type not between", value1, value2, "matchType");
            return this;
        }

        public Criteria andFeatureTypeIsNull() {
            addCriterion("feature_type is null");
            return this;
        }

        public Criteria andFeatureTypeIsNotNull() {
            addCriterion("feature_type is not null");
            return this;
        }

        public Criteria andFeatureTypeEqualTo(String value) {
            addCriterion("feature_type =", value, "featureType");
            return this;
        }

        public Criteria andFeatureTypeNotEqualTo(String value) {
            addCriterion("feature_type <>", value, "featureType");
            return this;
        }

        public Criteria andFeatureTypeGreaterThan(String value) {
            addCriterion("feature_type >", value, "featureType");
            return this;
        }

        public Criteria andFeatureTypeGreaterThanOrEqualTo(String value) {
            addCriterion("feature_type >=", value, "featureType");
            return this;
        }

        public Criteria andFeatureTypeLessThan(String value) {
            addCriterion("feature_type <", value, "featureType");
            return this;
        }

        public Criteria andFeatureTypeLessThanOrEqualTo(String value) {
            addCriterion("feature_type <=", value, "featureType");
            return this;
        }

        public Criteria andFeatureTypeLike(String value) {
            addCriterion("feature_type like", value, "featureType");
            return this;
        }

        public Criteria andFeatureTypeNotLike(String value) {
            addCriterion("feature_type not like", value, "featureType");
            return this;
        }

        public Criteria andFeatureTypeIn(List values) {
            addCriterion("feature_type in", values, "featureType");
            return this;
        }

        public Criteria andFeatureTypeNotIn(List values) {
            addCriterion("feature_type not in", values, "featureType");
            return this;
        }

        public Criteria andFeatureTypeBetween(String value1, String value2) {
            addCriterion("feature_type between", value1, value2, "featureType");
            return this;
        }

        public Criteria andFeatureTypeNotBetween(String value1, String value2) {
            addCriterion("feature_type not between", value1, value2, "featureType");
            return this;
        }

        public Criteria andFeatureIsNull() {
            addCriterion("feature is null");
            return this;
        }

        public Criteria andFeatureIsNotNull() {
            addCriterion("feature is not null");
            return this;
        }

        public Criteria andFeatureEqualTo(String value) {
            addCriterion("feature =", value, "feature");
            return this;
        }

        public Criteria andFeatureNotEqualTo(String value) {
            addCriterion("feature <>", value, "feature");
            return this;
        }

        public Criteria andFeatureGreaterThan(String value) {
            addCriterion("feature >", value, "feature");
            return this;
        }

        public Criteria andFeatureGreaterThanOrEqualTo(String value) {
            addCriterion("feature >=", value, "feature");
            return this;
        }

        public Criteria andFeatureLessThan(String value) {
            addCriterion("feature <", value, "feature");
            return this;
        }

        public Criteria andFeatureLessThanOrEqualTo(String value) {
            addCriterion("feature <=", value, "feature");
            return this;
        }

        public Criteria andFeatureLike(String value) {
            addCriterion("feature like", value, "feature");
            return this;
        }

        public Criteria andFeatureNotLike(String value) {
            addCriterion("feature not like", value, "feature");
            return this;
        }

        public Criteria andFeatureIn(List values) {
            addCriterion("feature in", values, "feature");
            return this;
        }

        public Criteria andFeatureNotIn(List values) {
            addCriterion("feature not in", values, "feature");
            return this;
        }

        public Criteria andFeatureBetween(String value1, String value2) {
            addCriterion("feature between", value1, value2, "feature");
            return this;
        }

        public Criteria andFeatureNotBetween(String value1, String value2) {
            addCriterion("feature not between", value1, value2, "feature");
            return this;
        }

        public Criteria andImeiIsNull() {
            addCriterion("imei is null");
            return this;
        }

        public Criteria andImeiIsNotNull() {
            addCriterion("imei is not null");
            return this;
        }

        public Criteria andImeiEqualTo(String value) {
            addCriterion("imei =", value, "imei");
            return this;
        }

        public Criteria andImeiNotEqualTo(String value) {
            addCriterion("imei <>", value, "imei");
            return this;
        }

        public Criteria andImeiGreaterThan(String value) {
            addCriterion("imei >", value, "imei");
            return this;
        }

        public Criteria andImeiGreaterThanOrEqualTo(String value) {
            addCriterion("imei >=", value, "imei");
            return this;
        }

        public Criteria andImeiLessThan(String value) {
            addCriterion("imei <", value, "imei");
            return this;
        }

        public Criteria andImeiLessThanOrEqualTo(String value) {
            addCriterion("imei <=", value, "imei");
            return this;
        }

        public Criteria andImeiLike(String value) {
            addCriterion("imei like", value, "imei");
            return this;
        }

        public Criteria andImeiNotLike(String value) {
            addCriterion("imei not like", value, "imei");
            return this;
        }

        public Criteria andImeiIn(List values) {
            addCriterion("imei in", values, "imei");
            return this;
        }

        public Criteria andImeiNotIn(List values) {
            addCriterion("imei not in", values, "imei");
            return this;
        }

        public Criteria andImeiBetween(String value1, String value2) {
            addCriterion("imei between", value1, value2, "imei");
            return this;
        }

        public Criteria andImeiNotBetween(String value1, String value2) {
            addCriterion("imei not between", value1, value2, "imei");
            return this;
        }

        public Criteria andMacIsNull() {
            addCriterion("mac is null");
            return this;
        }

        public Criteria andMacIsNotNull() {
            addCriterion("mac is not null");
            return this;
        }

        public Criteria andMacEqualTo(String value) {
            addCriterion("mac =", value, "mac");
            return this;
        }

        public Criteria andMacNotEqualTo(String value) {
            addCriterion("mac <>", value, "mac");
            return this;
        }

        public Criteria andMacGreaterThan(String value) {
            addCriterion("mac >", value, "mac");
            return this;
        }

        public Criteria andMacGreaterThanOrEqualTo(String value) {
            addCriterion("mac >=", value, "mac");
            return this;
        }

        public Criteria andMacLessThan(String value) {
            addCriterion("mac <", value, "mac");
            return this;
        }

        public Criteria andMacLessThanOrEqualTo(String value) {
            addCriterion("mac <=", value, "mac");
            return this;
        }

        public Criteria andMacLike(String value) {
            addCriterion("mac like", value, "mac");
            return this;
        }

        public Criteria andMacNotLike(String value) {
            addCriterion("mac not like", value, "mac");
            return this;
        }

        public Criteria andMacIn(List values) {
            addCriterion("mac in", values, "mac");
            return this;
        }

        public Criteria andMacNotIn(List values) {
            addCriterion("mac not in", values, "mac");
            return this;
        }

        public Criteria andMacBetween(String value1, String value2) {
            addCriterion("mac between", value1, value2, "mac");
            return this;
        }

        public Criteria andMacNotBetween(String value1, String value2) {
            addCriterion("mac not between", value1, value2, "mac");
            return this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("uid =", value, "uid");
            return this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("uid <>", value, "uid");
            return this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("uid >", value, "uid");
            return this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("uid >=", value, "uid");
            return this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("uid <", value, "uid");
            return this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("uid <=", value, "uid");
            return this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("uid like", value, "uid");
            return this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("uid not like", value, "uid");
            return this;
        }

        public Criteria andUidIn(List values) {
            addCriterion("uid in", values, "uid");
            return this;
        }

        public Criteria andUidNotIn(List values) {
            addCriterion("uid not in", values, "uid");
            return this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("uid between", value1, value2, "uid");
            return this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return this;
        }

        public Criteria andClientNameIsNull() {
            addCriterion("client_name is null");
            return this;
        }

        public Criteria andClientNameIsNotNull() {
            addCriterion("client_name is not null");
            return this;
        }

        public Criteria andClientNameEqualTo(String value) {
            addCriterion("client_name =", value, "clientName");
            return this;
        }

        public Criteria andClientNameNotEqualTo(String value) {
            addCriterion("client_name <>", value, "clientName");
            return this;
        }

        public Criteria andClientNameGreaterThan(String value) {
            addCriterion("client_name >", value, "clientName");
            return this;
        }

        public Criteria andClientNameGreaterThanOrEqualTo(String value) {
            addCriterion("client_name >=", value, "clientName");
            return this;
        }

        public Criteria andClientNameLessThan(String value) {
            addCriterion("client_name <", value, "clientName");
            return this;
        }

        public Criteria andClientNameLessThanOrEqualTo(String value) {
            addCriterion("client_name <=", value, "clientName");
            return this;
        }

        public Criteria andClientNameLike(String value) {
            addCriterion("client_name like", value, "clientName");
            return this;
        }

        public Criteria andClientNameNotLike(String value) {
            addCriterion("client_name not like", value, "clientName");
            return this;
        }

        public Criteria andClientNameIn(List values) {
            addCriterion("client_name in", values, "clientName");
            return this;
        }

        public Criteria andClientNameNotIn(List values) {
            addCriterion("client_name not in", values, "clientName");
            return this;
        }

        public Criteria andClientNameBetween(String value1, String value2) {
            addCriterion("client_name between", value1, value2, "clientName");
            return this;
        }

        public Criteria andClientNameNotBetween(String value1, String value2) {
            addCriterion("client_name not between", value1, value2, "clientName");
            return this;
        }

        public Criteria andClientIdIsNull() {
            addCriterion("client_id is null");
            return this;
        }

        public Criteria andClientIdIsNotNull() {
            addCriterion("client_id is not null");
            return this;
        }

        public Criteria andClientIdEqualTo(String value) {
            addCriterion("client_id =", value, "clientId");
            return this;
        }

        public Criteria andClientIdNotEqualTo(String value) {
            addCriterion("client_id <>", value, "clientId");
            return this;
        }

        public Criteria andClientIdGreaterThan(String value) {
            addCriterion("client_id >", value, "clientId");
            return this;
        }

        public Criteria andClientIdGreaterThanOrEqualTo(String value) {
            addCriterion("client_id >=", value, "clientId");
            return this;
        }

        public Criteria andClientIdLessThan(String value) {
            addCriterion("client_id <", value, "clientId");
            return this;
        }

        public Criteria andClientIdLessThanOrEqualTo(String value) {
            addCriterion("client_id <=", value, "clientId");
            return this;
        }

        public Criteria andClientIdLike(String value) {
            addCriterion("client_id like", value, "clientId");
            return this;
        }

        public Criteria andClientIdNotLike(String value) {
            addCriterion("client_id not like", value, "clientId");
            return this;
        }

        public Criteria andClientIdIn(List values) {
            addCriterion("client_id in", values, "clientId");
            return this;
        }

        public Criteria andClientIdNotIn(List values) {
            addCriterion("client_id not in", values, "clientId");
            return this;
        }

        public Criteria andClientIdBetween(String value1, String value2) {
            addCriterion("client_id between", value1, value2, "clientId");
            return this;
        }

        public Criteria andClientIdNotBetween(String value1, String value2) {
            addCriterion("client_id not between", value1, value2, "clientId");
            return this;
        }

        public Criteria andClientVersionIsNull() {
            addCriterion("client_version is null");
            return this;
        }

        public Criteria andClientVersionIsNotNull() {
            addCriterion("client_version is not null");
            return this;
        }

        public Criteria andClientVersionEqualTo(String value) {
            addCriterion("client_version =", value, "clientVersion");
            return this;
        }

        public Criteria andClientVersionNotEqualTo(String value) {
            addCriterion("client_version <>", value, "clientVersion");
            return this;
        }

        public Criteria andClientVersionGreaterThan(String value) {
            addCriterion("client_version >", value, "clientVersion");
            return this;
        }

        public Criteria andClientVersionGreaterThanOrEqualTo(String value) {
            addCriterion("client_version >=", value, "clientVersion");
            return this;
        }

        public Criteria andClientVersionLessThan(String value) {
            addCriterion("client_version <", value, "clientVersion");
            return this;
        }

        public Criteria andClientVersionLessThanOrEqualTo(String value) {
            addCriterion("client_version <=", value, "clientVersion");
            return this;
        }

        public Criteria andClientVersionLike(String value) {
            addCriterion("client_version like", value, "clientVersion");
            return this;
        }

        public Criteria andClientVersionNotLike(String value) {
            addCriterion("client_version not like", value, "clientVersion");
            return this;
        }

        public Criteria andClientVersionIn(List values) {
            addCriterion("client_version in", values, "clientVersion");
            return this;
        }

        public Criteria andClientVersionNotIn(List values) {
            addCriterion("client_version not in", values, "clientVersion");
            return this;
        }

        public Criteria andClientVersionBetween(String value1, String value2) {
            addCriterion("client_version between", value1, value2, "clientVersion");
            return this;
        }

        public Criteria andClientVersionNotBetween(String value1, String value2) {
            addCriterion("client_version not between", value1, value2, "clientVersion");
            return this;
        }

        public Criteria andCidIsNull() {
            addCriterion("cid is null");
            return this;
        }

        public Criteria andCidIsNotNull() {
            addCriterion("cid is not null");
            return this;
        }

        public Criteria andCidEqualTo(String value) {
            addCriterion("cid =", value, "cid");
            return this;
        }

        public Criteria andCidNotEqualTo(String value) {
            addCriterion("cid <>", value, "cid");
            return this;
        }

        public Criteria andCidGreaterThan(String value) {
            addCriterion("cid >", value, "cid");
            return this;
        }

        public Criteria andCidGreaterThanOrEqualTo(String value) {
            addCriterion("cid >=", value, "cid");
            return this;
        }

        public Criteria andCidLessThan(String value) {
            addCriterion("cid <", value, "cid");
            return this;
        }

        public Criteria andCidLessThanOrEqualTo(String value) {
            addCriterion("cid <=", value, "cid");
            return this;
        }

        public Criteria andCidLike(String value) {
            addCriterion("cid like", value, "cid");
            return this;
        }

        public Criteria andCidNotLike(String value) {
            addCriterion("cid not like", value, "cid");
            return this;
        }

        public Criteria andCidIn(List values) {
            addCriterion("cid in", values, "cid");
            return this;
        }

        public Criteria andCidNotIn(List values) {
            addCriterion("cid not in", values, "cid");
            return this;
        }

        public Criteria andCidBetween(String value1, String value2) {
            addCriterion("cid between", value1, value2, "cid");
            return this;
        }

        public Criteria andCidNotBetween(String value1, String value2) {
            addCriterion("cid not between", value1, value2, "cid");
            return this;
        }

        public Criteria andPhoneTypeIsNull() {
            addCriterion("phone_type is null");
            return this;
        }

        public Criteria andPhoneTypeIsNotNull() {
            addCriterion("phone_type is not null");
            return this;
        }

        public Criteria andPhoneTypeEqualTo(String value) {
            addCriterion("phone_type =", value, "phoneType");
            return this;
        }

        public Criteria andPhoneTypeNotEqualTo(String value) {
            addCriterion("phone_type <>", value, "phoneType");
            return this;
        }

        public Criteria andPhoneTypeGreaterThan(String value) {
            addCriterion("phone_type >", value, "phoneType");
            return this;
        }

        public Criteria andPhoneTypeGreaterThanOrEqualTo(String value) {
            addCriterion("phone_type >=", value, "phoneType");
            return this;
        }

        public Criteria andPhoneTypeLessThan(String value) {
            addCriterion("phone_type <", value, "phoneType");
            return this;
        }

        public Criteria andPhoneTypeLessThanOrEqualTo(String value) {
            addCriterion("phone_type <=", value, "phoneType");
            return this;
        }

        public Criteria andPhoneTypeLike(String value) {
            addCriterion("phone_type like", value, "phoneType");
            return this;
        }

        public Criteria andPhoneTypeNotLike(String value) {
            addCriterion("phone_type not like", value, "phoneType");
            return this;
        }

        public Criteria andPhoneTypeIn(List values) {
            addCriterion("phone_type in", values, "phoneType");
            return this;
        }

        public Criteria andPhoneTypeNotIn(List values) {
            addCriterion("phone_type not in", values, "phoneType");
            return this;
        }

        public Criteria andPhoneTypeBetween(String value1, String value2) {
            addCriterion("phone_type between", value1, value2, "phoneType");
            return this;
        }

        public Criteria andPhoneTypeNotBetween(String value1, String value2) {
            addCriterion("phone_type not between", value1, value2, "phoneType");
            return this;
        }

        public Criteria andLoginIpIsNull() {
            addCriterion("login_ip is null");
            return this;
        }

        public Criteria andLoginIpIsNotNull() {
            addCriterion("login_ip is not null");
            return this;
        }

        public Criteria andLoginIpEqualTo(String value) {
            addCriterion("login_ip =", value, "loginIp");
            return this;
        }

        public Criteria andLoginIpNotEqualTo(String value) {
            addCriterion("login_ip <>", value, "loginIp");
            return this;
        }

        public Criteria andLoginIpGreaterThan(String value) {
            addCriterion("login_ip >", value, "loginIp");
            return this;
        }

        public Criteria andLoginIpGreaterThanOrEqualTo(String value) {
            addCriterion("login_ip >=", value, "loginIp");
            return this;
        }

        public Criteria andLoginIpLessThan(String value) {
            addCriterion("login_ip <", value, "loginIp");
            return this;
        }

        public Criteria andLoginIpLessThanOrEqualTo(String value) {
            addCriterion("login_ip <=", value, "loginIp");
            return this;
        }

        public Criteria andLoginIpLike(String value) {
            addCriterion("login_ip like", value, "loginIp");
            return this;
        }

        public Criteria andLoginIpNotLike(String value) {
            addCriterion("login_ip not like", value, "loginIp");
            return this;
        }

        public Criteria andLoginIpIn(List values) {
            addCriterion("login_ip in", values, "loginIp");
            return this;
        }

        public Criteria andLoginIpNotIn(List values) {
            addCriterion("login_ip not in", values, "loginIp");
            return this;
        }

        public Criteria andLoginIpBetween(String value1, String value2) {
            addCriterion("login_ip between", value1, value2, "loginIp");
            return this;
        }

        public Criteria andLoginIpNotBetween(String value1, String value2) {
            addCriterion("login_ip not between", value1, value2, "loginIp");
            return this;
        }

        public Criteria andEventIdIsNull() {
            addCriterion("event_id is null");
            return this;
        }

        public Criteria andEventIdIsNotNull() {
            addCriterion("event_id is not null");
            return this;
        }

        public Criteria andEventIdEqualTo(String value) {
            addCriterion("event_id =", value, "eventId");
            return this;
        }

        public Criteria andEventIdNotEqualTo(String value) {
            addCriterion("event_id <>", value, "eventId");
            return this;
        }

        public Criteria andEventIdGreaterThan(String value) {
            addCriterion("event_id >", value, "eventId");
            return this;
        }

        public Criteria andEventIdGreaterThanOrEqualTo(String value) {
            addCriterion("event_id >=", value, "eventId");
            return this;
        }

        public Criteria andEventIdLessThan(String value) {
            addCriterion("event_id <", value, "eventId");
            return this;
        }

        public Criteria andEventIdLessThanOrEqualTo(String value) {
            addCriterion("event_id <=", value, "eventId");
            return this;
        }

        public Criteria andEventIdLike(String value) {
            addCriterion("event_id like", value, "eventId");
            return this;
        }

        public Criteria andEventIdNotLike(String value) {
            addCriterion("event_id not like", value, "eventId");
            return this;
        }

        public Criteria andEventIdIn(List values) {
            addCriterion("event_id in", values, "eventId");
            return this;
        }

        public Criteria andEventIdNotIn(List values) {
            addCriterion("event_id not in", values, "eventId");
            return this;
        }

        public Criteria andEventIdBetween(String value1, String value2) {
            addCriterion("event_id between", value1, value2, "eventId");
            return this;
        }

        public Criteria andEventIdNotBetween(String value1, String value2) {
            addCriterion("event_id not between", value1, value2, "eventId");
            return this;
        }

        public Criteria andEventValueIsNull() {
            addCriterion("event_value is null");
            return this;
        }

        public Criteria andEventValueIsNotNull() {
            addCriterion("event_value is not null");
            return this;
        }

        public Criteria andEventValueEqualTo(String value) {
            addCriterion("event_value =", value, "eventValue");
            return this;
        }

        public Criteria andEventValueNotEqualTo(String value) {
            addCriterion("event_value <>", value, "eventValue");
            return this;
        }

        public Criteria andEventValueGreaterThan(String value) {
            addCriterion("event_value >", value, "eventValue");
            return this;
        }

        public Criteria andEventValueGreaterThanOrEqualTo(String value) {
            addCriterion("event_value >=", value, "eventValue");
            return this;
        }

        public Criteria andEventValueLessThan(String value) {
            addCriterion("event_value <", value, "eventValue");
            return this;
        }

        public Criteria andEventValueLessThanOrEqualTo(String value) {
            addCriterion("event_value <=", value, "eventValue");
            return this;
        }

        public Criteria andEventValueLike(String value) {
            addCriterion("event_value like", value, "eventValue");
            return this;
        }

        public Criteria andEventValueNotLike(String value) {
            addCriterion("event_value not like", value, "eventValue");
            return this;
        }

        public Criteria andEventValueIn(List values) {
            addCriterion("event_value in", values, "eventValue");
            return this;
        }

        public Criteria andEventValueNotIn(List values) {
            addCriterion("event_value not in", values, "eventValue");
            return this;
        }

        public Criteria andEventValueBetween(String value1, String value2) {
            addCriterion("event_value between", value1, value2, "eventValue");
            return this;
        }

        public Criteria andEventValueNotBetween(String value1, String value2) {
            addCriterion("event_value not between", value1, value2, "eventValue");
            return this;
        }

        public Criteria andEventSourceIsNull() {
            addCriterion("event_source is null");
            return this;
        }

        public Criteria andEventSourceIsNotNull() {
            addCriterion("event_source is not null");
            return this;
        }

        public Criteria andEventSourceEqualTo(String value) {
            addCriterion("event_source =", value, "eventSource");
            return this;
        }

        public Criteria andEventSourceNotEqualTo(String value) {
            addCriterion("event_source <>", value, "eventSource");
            return this;
        }

        public Criteria andEventSourceGreaterThan(String value) {
            addCriterion("event_source >", value, "eventSource");
            return this;
        }

        public Criteria andEventSourceGreaterThanOrEqualTo(String value) {
            addCriterion("event_source >=", value, "eventSource");
            return this;
        }

        public Criteria andEventSourceLessThan(String value) {
            addCriterion("event_source <", value, "eventSource");
            return this;
        }

        public Criteria andEventSourceLessThanOrEqualTo(String value) {
            addCriterion("event_source <=", value, "eventSource");
            return this;
        }

        public Criteria andEventSourceLike(String value) {
            addCriterion("event_source like", value, "eventSource");
            return this;
        }

        public Criteria andEventSourceNotLike(String value) {
            addCriterion("event_source not like", value, "eventSource");
            return this;
        }

        public Criteria andEventSourceIn(List values) {
            addCriterion("event_source in", values, "eventSource");
            return this;
        }

        public Criteria andEventSourceNotIn(List values) {
            addCriterion("event_source not in", values, "eventSource");
            return this;
        }

        public Criteria andEventSourceBetween(String value1, String value2) {
            addCriterion("event_source between", value1, value2, "eventSource");
            return this;
        }

        public Criteria andEventSourceNotBetween(String value1, String value2) {
            addCriterion("event_source not between", value1, value2, "eventSource");
            return this;
        }

        public Criteria andInsertTimeIsNull() {
            addCriterion("insert_time is null");
            return this;
        }

        public Criteria andInsertTimeIsNotNull() {
            addCriterion("insert_time is not null");
            return this;
        }

        public Criteria andInsertTimeEqualTo(Date value) {
            addCriterion("insert_time =", value, "insertTime");
            return this;
        }

        public Criteria andInsertTimeNotEqualTo(Date value) {
            addCriterion("insert_time <>", value, "insertTime");
            return this;
        }

        public Criteria andInsertTimeGreaterThan(Date value) {
            addCriterion("insert_time >", value, "insertTime");
            return this;
        }

        public Criteria andInsertTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("insert_time >=", value, "insertTime");
            return this;
        }

        public Criteria andInsertTimeLessThan(Date value) {
            addCriterion("insert_time <", value, "insertTime");
            return this;
        }

        public Criteria andInsertTimeLessThanOrEqualTo(Date value) {
            addCriterion("insert_time <=", value, "insertTime");
            return this;
        }

        public Criteria andInsertTimeIn(List values) {
            addCriterion("insert_time in", values, "insertTime");
            return this;
        }

        public Criteria andInsertTimeNotIn(List values) {
            addCriterion("insert_time not in", values, "insertTime");
            return this;
        }

        public Criteria andInsertTimeBetween(Date value1, Date value2) {
            addCriterion("insert_time between", value1, value2, "insertTime");
            return this;
        }

        public Criteria andInsertTimeNotBetween(Date value1, Date value2) {
            addCriterion("insert_time not between", value1, value2, "insertTime");
            return this;
        }

        public Criteria andPackageNameIsNull() {
            addCriterion("package_name is null");
            return this;
        }

        public Criteria andPackageNameIsNotNull() {
            addCriterion("package_name is not null");
            return this;
        }

        public Criteria andPackageNameEqualTo(String value) {
            addCriterion("package_name =", value, "packageName");
            return this;
        }

        public Criteria andPackageNameNotEqualTo(String value) {
            addCriterion("package_name <>", value, "packageName");
            return this;
        }

        public Criteria andPackageNameGreaterThan(String value) {
            addCriterion("package_name >", value, "packageName");
            return this;
        }

        public Criteria andPackageNameGreaterThanOrEqualTo(String value) {
            addCriterion("package_name >=", value, "packageName");
            return this;
        }

        public Criteria andPackageNameLessThan(String value) {
            addCriterion("package_name <", value, "packageName");
            return this;
        }

        public Criteria andPackageNameLessThanOrEqualTo(String value) {
            addCriterion("package_name <=", value, "packageName");
            return this;
        }

        public Criteria andPackageNameLike(String value) {
            addCriterion("package_name like", value, "packageName");
            return this;
        }

        public Criteria andPackageNameNotLike(String value) {
            addCriterion("package_name not like", value, "packageName");
            return this;
        }

        public Criteria andPackageNameIn(List values) {
            addCriterion("package_name in", values, "packageName");
            return this;
        }

        public Criteria andPackageNameNotIn(List values) {
            addCriterion("package_name not in", values, "packageName");
            return this;
        }

        public Criteria andPackageNameBetween(String value1, String value2) {
            addCriterion("package_name between", value1, value2, "packageName");
            return this;
        }

        public Criteria andPackageNameNotBetween(String value1, String value2) {
            addCriterion("package_name not between", value1, value2, "packageName");
            return this;
        }
    }
}