package com.wangli.data.etl.report.gfanmarket.module;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class ClientEventLog {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.id
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.data_time
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String dataTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.version
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String version;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.method
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String method;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.platform
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String platform;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.screen_size
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String screenSize;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.match_type
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String matchType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.feature_type
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String featureType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.feature
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String feature;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.imei
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String imei;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.mac
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String mac;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.uid
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String uid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.client_name
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String clientName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.client_id
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String clientId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.client_version
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String clientVersion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.cid
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String cid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.phone_type
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String phoneType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.login_ip
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String loginIp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.event_id
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String eventId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.event_value
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String eventValue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.event_source
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String eventSource;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.insert_time
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private Date insertTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.package_name
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String packageName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column client_event_log.args
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private String args;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.id
     *
     * @return the value of client_event_log.id
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    private Map<String,Object> argMap = new HashMap<String,Object>();
    
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.id
     *
     * @param id the value for client_event_log.id
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.data_time
     *
     * @return the value of client_event_log.data_time
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.data_time
     *
     * @param dataTime the value for client_event_log.data_time
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setDataTime(String dataTime) {
        this.dataTime = dataTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.version
     *
     * @return the value of client_event_log.version
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.version
     *
     * @param version the value for client_event_log.version
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.method
     *
     * @return the value of client_event_log.method
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.method
     *
     * @param method the value for client_event_log.method
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.platform
     *
     * @return the value of client_event_log.platform
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.platform
     *
     * @param platform the value for client_event_log.platform
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.screen_size
     *
     * @return the value of client_event_log.screen_size
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getScreenSize() {
        return screenSize;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.screen_size
     *
     * @param screenSize the value for client_event_log.screen_size
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setScreenSize(String screenSize) {
        this.screenSize = screenSize;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.match_type
     *
     * @return the value of client_event_log.match_type
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getMatchType() {
        return matchType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.match_type
     *
     * @param matchType the value for client_event_log.match_type
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setMatchType(String matchType) {
        this.matchType = matchType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.feature_type
     *
     * @return the value of client_event_log.feature_type
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getFeatureType() {
        return featureType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.feature_type
     *
     * @param featureType the value for client_event_log.feature_type
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setFeatureType(String featureType) {
        this.featureType = featureType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.feature
     *
     * @return the value of client_event_log.feature
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.feature
     *
     * @param feature the value for client_event_log.feature
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setFeature(String feature) {
        this.feature = feature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.imei
     *
     * @return the value of client_event_log.imei
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.imei
     *
     * @param imei the value for client_event_log.imei
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.mac
     *
     * @return the value of client_event_log.mac
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.mac
     *
     * @param mac the value for client_event_log.mac
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.uid
     *
     * @return the value of client_event_log.uid
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.uid
     *
     * @param uid the value for client_event_log.uid
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.client_name
     *
     * @return the value of client_event_log.client_name
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.client_name
     *
     * @param clientName the value for client_event_log.client_name
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.client_id
     *
     * @return the value of client_event_log.client_id
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.client_id
     *
     * @param clientId the value for client_event_log.client_id
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.client_version
     *
     * @return the value of client_event_log.client_version
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getClientVersion() {
        return clientVersion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.client_version
     *
     * @param clientVersion the value for client_event_log.client_version
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setClientVersion(String clientVersion) {
        this.clientVersion = clientVersion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.cid
     *
     * @return the value of client_event_log.cid
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.cid
     *
     * @param cid the value for client_event_log.cid
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.phone_type
     *
     * @return the value of client_event_log.phone_type
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getPhoneType() {
        return phoneType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.phone_type
     *
     * @param phoneType the value for client_event_log.phone_type
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setPhoneType(String phoneType) {
        this.phoneType = phoneType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.login_ip
     *
     * @return the value of client_event_log.login_ip
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.login_ip
     *
     * @param loginIp the value for client_event_log.login_ip
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.event_id
     *
     * @return the value of client_event_log.event_id
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.event_id
     *
     * @param eventId the value for client_event_log.event_id
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.event_value
     *
     * @return the value of client_event_log.event_value
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getEventValue() {
        return eventValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.event_value
     *
     * @param eventValue the value for client_event_log.event_value
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setEventValue(String eventValue) {
        this.eventValue = eventValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.event_source
     *
     * @return the value of client_event_log.event_source
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getEventSource() {
        return eventSource;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.event_source
     *
     * @param eventSource the value for client_event_log.event_source
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setEventSource(String eventSource) {
        this.eventSource = eventSource;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.insert_time
     *
     * @return the value of client_event_log.insert_time
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.insert_time
     *
     * @param insertTime the value for client_event_log.insert_time
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.package_name
     *
     * @return the value of client_event_log.package_name
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.package_name
     *
     * @param packageName the value for client_event_log.package_name
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column client_event_log.args
     *
     * @return the value of client_event_log.args
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public String getArgs() {
        return args;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column client_event_log.args
     *
     * @param args the value for client_event_log.args
     *
     * @ibatorgenerated Fri Nov 21 15:50:59 CST 2014
     */
    public void setArgs(String args) {
        this.args = args;
    }

	public Map<String, Object> getArgMap() {
		return argMap;
	}

	public void setArgMap(Map<String, Object> argMap) {
		this.argMap = argMap;
	}
    
}