package com.wangli.data.etl.report.gfanmarket.module;

import java.util.Date;

public class GfanClientEventBannerclick {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.id
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.behavior_id
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private Integer behaviorId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.data_time
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private String dataTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.imei
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private String imei;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.client_name
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private String clientName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.client_id
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private String clientId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.client_version
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private String clientVersion;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.cid
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private String cid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.event_id
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private String eventId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.event_value
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private String eventValue;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.event_source
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private String eventSource;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.pid
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private String pid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.banner_id
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private Integer bannerId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.banner_type
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private String bannerType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.logTime
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private Date logtime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.insert_time
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private Date insertTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column gfan_client_event_bannerclick.args
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	private String args;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.id
	 * @return  the value of gfan_client_event_bannerclick.id
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.id
	 * @param id  the value for gfan_client_event_bannerclick.id
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.behavior_id
	 * @return  the value of gfan_client_event_bannerclick.behavior_id
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public Integer getBehaviorId() {
		return behaviorId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.behavior_id
	 * @param behaviorId  the value for gfan_client_event_bannerclick.behavior_id
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setBehaviorId(Integer behaviorId) {
		this.behaviorId = behaviorId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.data_time
	 * @return  the value of gfan_client_event_bannerclick.data_time
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public String getDataTime() {
		return dataTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.data_time
	 * @param dataTime  the value for gfan_client_event_bannerclick.data_time
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setDataTime(String dataTime) {
		this.dataTime = dataTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.imei
	 * @return  the value of gfan_client_event_bannerclick.imei
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public String getImei() {
		return imei;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.imei
	 * @param imei  the value for gfan_client_event_bannerclick.imei
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setImei(String imei) {
		this.imei = imei;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.client_name
	 * @return  the value of gfan_client_event_bannerclick.client_name
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public String getClientName() {
		return clientName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.client_name
	 * @param clientName  the value for gfan_client_event_bannerclick.client_name
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.client_id
	 * @return  the value of gfan_client_event_bannerclick.client_id
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public String getClientId() {
		return clientId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.client_id
	 * @param clientId  the value for gfan_client_event_bannerclick.client_id
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.client_version
	 * @return  the value of gfan_client_event_bannerclick.client_version
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public String getClientVersion() {
		return clientVersion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.client_version
	 * @param clientVersion  the value for gfan_client_event_bannerclick.client_version
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setClientVersion(String clientVersion) {
		this.clientVersion = clientVersion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.cid
	 * @return  the value of gfan_client_event_bannerclick.cid
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public String getCid() {
		return cid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.cid
	 * @param cid  the value for gfan_client_event_bannerclick.cid
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setCid(String cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.event_id
	 * @return  the value of gfan_client_event_bannerclick.event_id
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public String getEventId() {
		return eventId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.event_id
	 * @param eventId  the value for gfan_client_event_bannerclick.event_id
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.event_value
	 * @return  the value of gfan_client_event_bannerclick.event_value
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public String getEventValue() {
		return eventValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.event_value
	 * @param eventValue  the value for gfan_client_event_bannerclick.event_value
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setEventValue(String eventValue) {
		this.eventValue = eventValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.event_source
	 * @return  the value of gfan_client_event_bannerclick.event_source
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public String getEventSource() {
		return eventSource;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.event_source
	 * @param eventSource  the value for gfan_client_event_bannerclick.event_source
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setEventSource(String eventSource) {
		this.eventSource = eventSource;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.pid
	 * @return  the value of gfan_client_event_bannerclick.pid
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public String getPid() {
		return pid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.pid
	 * @param pid  the value for gfan_client_event_bannerclick.pid
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setPid(String pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.banner_id
	 * @return  the value of gfan_client_event_bannerclick.banner_id
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public Integer getBannerId() {
		return bannerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.banner_id
	 * @param bannerId  the value for gfan_client_event_bannerclick.banner_id
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setBannerId(Integer bannerId) {
		this.bannerId = bannerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.banner_type
	 * @return  the value of gfan_client_event_bannerclick.banner_type
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public String getBannerType() {
		return bannerType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.banner_type
	 * @param bannerType  the value for gfan_client_event_bannerclick.banner_type
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setBannerType(String bannerType) {
		this.bannerType = bannerType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.logTime
	 * @return  the value of gfan_client_event_bannerclick.logTime
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public Date getLogtime() {
		return logtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.logTime
	 * @param logtime  the value for gfan_client_event_bannerclick.logTime
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setLogtime(Date logtime) {
		this.logtime = logtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.insert_time
	 * @return  the value of gfan_client_event_bannerclick.insert_time
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.insert_time
	 * @param insertTime  the value for gfan_client_event_bannerclick.insert_time
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column gfan_client_event_bannerclick.args
	 * @return  the value of gfan_client_event_bannerclick.args
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public String getArgs() {
		return args;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column gfan_client_event_bannerclick.args
	 * @param args  the value for gfan_client_event_bannerclick.args
	 * @ibatorgenerated  Fri Nov 28 11:13:57 CST 2014
	 */
	public void setArgs(String args) {
		this.args = args;
	}
}