package com.wangli.data.etl.report.gfanmarket.module;

import java.util.Date;

public class GfanClientEventClick {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gfan_client_event_click.id
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gfan_client_event_click.behavior_id
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private Integer behaviorId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gfan_client_event_click.data_time
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private String dataTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gfan_client_event_click.imei
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private String imei;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gfan_client_event_click.client_name
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private String clientName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gfan_client_event_click.client_id
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private String clientId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gfan_client_event_click.client_version
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private String clientVersion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gfan_client_event_click.cid
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private String cid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gfan_client_event_click.event_id
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private String eventId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gfan_client_event_click.event_value
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private String eventValue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gfan_client_event_click.event_source
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private String eventSource;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gfan_client_event_click.pid
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private String pid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gfan_client_event_click.logTime
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private Date logtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gfan_client_event_click.insert_time
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private Date insertTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column gfan_client_event_click.args
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    private String args;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gfan_client_event_click.id
     *
     * @return the value of gfan_client_event_click.id
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gfan_client_event_click.id
     *
     * @param id the value for gfan_client_event_click.id
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gfan_client_event_click.behavior_id
     *
     * @return the value of gfan_client_event_click.behavior_id
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public Integer getBehaviorId() {
        return behaviorId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gfan_client_event_click.behavior_id
     *
     * @param behaviorId the value for gfan_client_event_click.behavior_id
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void setBehaviorId(Integer behaviorId) {
        this.behaviorId = behaviorId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gfan_client_event_click.data_time
     *
     * @return the value of gfan_client_event_click.data_time
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public String getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gfan_client_event_click.data_time
     *
     * @param dataTime the value for gfan_client_event_click.data_time
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void setDataTime(String dataTime) {
        this.dataTime = dataTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gfan_client_event_click.imei
     *
     * @return the value of gfan_client_event_click.imei
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gfan_client_event_click.imei
     *
     * @param imei the value for gfan_client_event_click.imei
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gfan_client_event_click.client_name
     *
     * @return the value of gfan_client_event_click.client_name
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gfan_client_event_click.client_name
     *
     * @param clientName the value for gfan_client_event_click.client_name
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gfan_client_event_click.client_id
     *
     * @return the value of gfan_client_event_click.client_id
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gfan_client_event_click.client_id
     *
     * @param clientId the value for gfan_client_event_click.client_id
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gfan_client_event_click.client_version
     *
     * @return the value of gfan_client_event_click.client_version
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public String getClientVersion() {
        return clientVersion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gfan_client_event_click.client_version
     *
     * @param clientVersion the value for gfan_client_event_click.client_version
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void setClientVersion(String clientVersion) {
        this.clientVersion = clientVersion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gfan_client_event_click.cid
     *
     * @return the value of gfan_client_event_click.cid
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gfan_client_event_click.cid
     *
     * @param cid the value for gfan_client_event_click.cid
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gfan_client_event_click.event_id
     *
     * @return the value of gfan_client_event_click.event_id
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gfan_client_event_click.event_id
     *
     * @param eventId the value for gfan_client_event_click.event_id
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gfan_client_event_click.event_value
     *
     * @return the value of gfan_client_event_click.event_value
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public String getEventValue() {
        return eventValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gfan_client_event_click.event_value
     *
     * @param eventValue the value for gfan_client_event_click.event_value
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void setEventValue(String eventValue) {
        this.eventValue = eventValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gfan_client_event_click.event_source
     *
     * @return the value of gfan_client_event_click.event_source
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public String getEventSource() {
        return eventSource;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gfan_client_event_click.event_source
     *
     * @param eventSource the value for gfan_client_event_click.event_source
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void setEventSource(String eventSource) {
        this.eventSource = eventSource;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gfan_client_event_click.pid
     *
     * @return the value of gfan_client_event_click.pid
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gfan_client_event_click.pid
     *
     * @param pid the value for gfan_client_event_click.pid
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gfan_client_event_click.logTime
     *
     * @return the value of gfan_client_event_click.logTime
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public Date getLogtime() {
        return logtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gfan_client_event_click.logTime
     *
     * @param logtime the value for gfan_client_event_click.logTime
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void setLogtime(Date logtime) {
        this.logtime = logtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gfan_client_event_click.insert_time
     *
     * @return the value of gfan_client_event_click.insert_time
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gfan_client_event_click.insert_time
     *
     * @param insertTime the value for gfan_client_event_click.insert_time
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gfan_client_event_click.args
     *
     * @return the value of gfan_client_event_click.args
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public String getArgs() {
        return args;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gfan_client_event_click.args
     *
     * @param args the value for gfan_client_event_click.args
     *
     * @ibatorgenerated Wed Dec 10 16:10:59 CST 2014
     */
    public void setArgs(String args) {
        this.args = args;
    }
}