package com.wangli.data.etl.report.gfanmarket.module;

import java.util.Date;

public class SearchHotwordsLog {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column search_hotwords_log.id
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column search_hotwords_log.data_time
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	private String dataTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column search_hotwords_log.rank
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	private Integer rank;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column search_hotwords_log.hotwords
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	private String hotwords;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column search_hotwords_log.insert_time
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	private Date insertTime;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column search_hotwords_log.id
	 * @return  the value of search_hotwords_log.id
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column search_hotwords_log.id
	 * @param id  the value for search_hotwords_log.id
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column search_hotwords_log.data_time
	 * @return  the value of search_hotwords_log.data_time
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	public String getDataTime() {
		return dataTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column search_hotwords_log.data_time
	 * @param dataTime  the value for search_hotwords_log.data_time
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	public void setDataTime(String dataTime) {
		this.dataTime = dataTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column search_hotwords_log.rank
	 * @return  the value of search_hotwords_log.rank
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	public Integer getRank() {
		return rank;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column search_hotwords_log.rank
	 * @param rank  the value for search_hotwords_log.rank
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	public void setRank(Integer rank) {
		this.rank = rank;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column search_hotwords_log.hotwords
	 * @return  the value of search_hotwords_log.hotwords
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	public String getHotwords() {
		return hotwords;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column search_hotwords_log.hotwords
	 * @param hotwords  the value for search_hotwords_log.hotwords
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	public void setHotwords(String hotwords) {
		this.hotwords = hotwords;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column search_hotwords_log.insert_time
	 * @return  the value of search_hotwords_log.insert_time
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column search_hotwords_log.insert_time
	 * @param insertTime  the value for search_hotwords_log.insert_time
	 * @ibatorgenerated  Thu Dec 11 19:28:48 CST 2014
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}
}