package com.wangli.data.analysis.ar.adc.module;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class CorpOrderExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public CorpOrderExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    protected CorpOrderExample(CorpOrderExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table corp_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("order_id =", value, "orderId");
            return this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "orderId");
            return this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("order_id >", value, "orderId");
            return this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "orderId");
            return this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("order_id <", value, "orderId");
            return this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "orderId");
            return this;
        }

        public Criteria andOrderIdIn(List values) {
            addCriterion("order_id in", values, "orderId");
            return this;
        }

        public Criteria andOrderIdNotIn(List values) {
            addCriterion("order_id not in", values, "orderId");
            return this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return this;
        }

        public Criteria andOrderCodeIsNull() {
            addCriterion("order_code is null");
            return this;
        }

        public Criteria andOrderCodeIsNotNull() {
            addCriterion("order_code is not null");
            return this;
        }

        public Criteria andOrderCodeEqualTo(String value) {
            addCriterion("order_code =", value, "orderCode");
            return this;
        }

        public Criteria andOrderCodeNotEqualTo(String value) {
            addCriterion("order_code <>", value, "orderCode");
            return this;
        }

        public Criteria andOrderCodeGreaterThan(String value) {
            addCriterion("order_code >", value, "orderCode");
            return this;
        }

        public Criteria andOrderCodeGreaterThanOrEqualTo(String value) {
            addCriterion("order_code >=", value, "orderCode");
            return this;
        }

        public Criteria andOrderCodeLessThan(String value) {
            addCriterion("order_code <", value, "orderCode");
            return this;
        }

        public Criteria andOrderCodeLessThanOrEqualTo(String value) {
            addCriterion("order_code <=", value, "orderCode");
            return this;
        }

        public Criteria andOrderCodeLike(String value) {
            addCriterion("order_code like", value, "orderCode");
            return this;
        }

        public Criteria andOrderCodeNotLike(String value) {
            addCriterion("order_code not like", value, "orderCode");
            return this;
        }

        public Criteria andOrderCodeIn(List values) {
            addCriterion("order_code in", values, "orderCode");
            return this;
        }

        public Criteria andOrderCodeNotIn(List values) {
            addCriterion("order_code not in", values, "orderCode");
            return this;
        }

        public Criteria andOrderCodeBetween(String value1, String value2) {
            addCriterion("order_code between", value1, value2, "orderCode");
            return this;
        }

        public Criteria andOrderCodeNotBetween(String value1, String value2) {
            addCriterion("order_code not between", value1, value2, "orderCode");
            return this;
        }

        public Criteria andOrderNameIsNull() {
            addCriterion("order_name is null");
            return this;
        }

        public Criteria andOrderNameIsNotNull() {
            addCriterion("order_name is not null");
            return this;
        }

        public Criteria andOrderNameEqualTo(String value) {
            addCriterion("order_name =", value, "orderName");
            return this;
        }

        public Criteria andOrderNameNotEqualTo(String value) {
            addCriterion("order_name <>", value, "orderName");
            return this;
        }

        public Criteria andOrderNameGreaterThan(String value) {
            addCriterion("order_name >", value, "orderName");
            return this;
        }

        public Criteria andOrderNameGreaterThanOrEqualTo(String value) {
            addCriterion("order_name >=", value, "orderName");
            return this;
        }

        public Criteria andOrderNameLessThan(String value) {
            addCriterion("order_name <", value, "orderName");
            return this;
        }

        public Criteria andOrderNameLessThanOrEqualTo(String value) {
            addCriterion("order_name <=", value, "orderName");
            return this;
        }

        public Criteria andOrderNameLike(String value) {
            addCriterion("order_name like", value, "orderName");
            return this;
        }

        public Criteria andOrderNameNotLike(String value) {
            addCriterion("order_name not like", value, "orderName");
            return this;
        }

        public Criteria andOrderNameIn(List values) {
            addCriterion("order_name in", values, "orderName");
            return this;
        }

        public Criteria andOrderNameNotIn(List values) {
            addCriterion("order_name not in", values, "orderName");
            return this;
        }

        public Criteria andOrderNameBetween(String value1, String value2) {
            addCriterion("order_name between", value1, value2, "orderName");
            return this;
        }

        public Criteria andOrderNameNotBetween(String value1, String value2) {
            addCriterion("order_name not between", value1, value2, "orderName");
            return this;
        }

        public Criteria andContractIdIsNull() {
            addCriterion("contract_id is null");
            return this;
        }

        public Criteria andContractIdIsNotNull() {
            addCriterion("contract_id is not null");
            return this;
        }

        public Criteria andContractIdEqualTo(String value) {
            addCriterion("contract_id =", value, "contractId");
            return this;
        }

        public Criteria andContractIdNotEqualTo(String value) {
            addCriterion("contract_id <>", value, "contractId");
            return this;
        }

        public Criteria andContractIdGreaterThan(String value) {
            addCriterion("contract_id >", value, "contractId");
            return this;
        }

        public Criteria andContractIdGreaterThanOrEqualTo(String value) {
            addCriterion("contract_id >=", value, "contractId");
            return this;
        }

        public Criteria andContractIdLessThan(String value) {
            addCriterion("contract_id <", value, "contractId");
            return this;
        }

        public Criteria andContractIdLessThanOrEqualTo(String value) {
            addCriterion("contract_id <=", value, "contractId");
            return this;
        }

        public Criteria andContractIdLike(String value) {
            addCriterion("contract_id like", value, "contractId");
            return this;
        }

        public Criteria andContractIdNotLike(String value) {
            addCriterion("contract_id not like", value, "contractId");
            return this;
        }

        public Criteria andContractIdIn(List values) {
            addCriterion("contract_id in", values, "contractId");
            return this;
        }

        public Criteria andContractIdNotIn(List values) {
            addCriterion("contract_id not in", values, "contractId");
            return this;
        }

        public Criteria andContractIdBetween(String value1, String value2) {
            addCriterion("contract_id between", value1, value2, "contractId");
            return this;
        }

        public Criteria andContractIdNotBetween(String value1, String value2) {
            addCriterion("contract_id not between", value1, value2, "contractId");
            return this;
        }

        public Criteria andOrderTypeIsNull() {
            addCriterion("order_type is null");
            return this;
        }

        public Criteria andOrderTypeIsNotNull() {
            addCriterion("order_type is not null");
            return this;
        }

        public Criteria andOrderTypeEqualTo(Byte value) {
            addCriterion("order_type =", value, "orderType");
            return this;
        }

        public Criteria andOrderTypeNotEqualTo(Byte value) {
            addCriterion("order_type <>", value, "orderType");
            return this;
        }

        public Criteria andOrderTypeGreaterThan(Byte value) {
            addCriterion("order_type >", value, "orderType");
            return this;
        }

        public Criteria andOrderTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("order_type >=", value, "orderType");
            return this;
        }

        public Criteria andOrderTypeLessThan(Byte value) {
            addCriterion("order_type <", value, "orderType");
            return this;
        }

        public Criteria andOrderTypeLessThanOrEqualTo(Byte value) {
            addCriterion("order_type <=", value, "orderType");
            return this;
        }

        public Criteria andOrderTypeIn(List values) {
            addCriterion("order_type in", values, "orderType");
            return this;
        }

        public Criteria andOrderTypeNotIn(List values) {
            addCriterion("order_type not in", values, "orderType");
            return this;
        }

        public Criteria andOrderTypeBetween(Byte value1, Byte value2) {
            addCriterion("order_type between", value1, value2, "orderType");
            return this;
        }

        public Criteria andOrderTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("order_type not between", value1, value2, "orderType");
            return this;
        }

        public Criteria andPackageModeIsNull() {
            addCriterion("package_mode is null");
            return this;
        }

        public Criteria andPackageModeIsNotNull() {
            addCriterion("package_mode is not null");
            return this;
        }

        public Criteria andPackageModeEqualTo(Byte value) {
            addCriterion("package_mode =", value, "packageMode");
            return this;
        }

        public Criteria andPackageModeNotEqualTo(Byte value) {
            addCriterion("package_mode <>", value, "packageMode");
            return this;
        }

        public Criteria andPackageModeGreaterThan(Byte value) {
            addCriterion("package_mode >", value, "packageMode");
            return this;
        }

        public Criteria andPackageModeGreaterThanOrEqualTo(Byte value) {
            addCriterion("package_mode >=", value, "packageMode");
            return this;
        }

        public Criteria andPackageModeLessThan(Byte value) {
            addCriterion("package_mode <", value, "packageMode");
            return this;
        }

        public Criteria andPackageModeLessThanOrEqualTo(Byte value) {
            addCriterion("package_mode <=", value, "packageMode");
            return this;
        }

        public Criteria andPackageModeIn(List values) {
            addCriterion("package_mode in", values, "packageMode");
            return this;
        }

        public Criteria andPackageModeNotIn(List values) {
            addCriterion("package_mode not in", values, "packageMode");
            return this;
        }

        public Criteria andPackageModeBetween(Byte value1, Byte value2) {
            addCriterion("package_mode between", value1, value2, "packageMode");
            return this;
        }

        public Criteria andPackageModeNotBetween(Byte value1, Byte value2) {
            addCriterion("package_mode not between", value1, value2, "packageMode");
            return this;
        }

        public Criteria andBuildIdIsNull() {
            addCriterion("build_id is null");
            return this;
        }

        public Criteria andBuildIdIsNotNull() {
            addCriterion("build_id is not null");
            return this;
        }

        public Criteria andBuildIdEqualTo(Integer value) {
            addCriterion("build_id =", value, "buildId");
            return this;
        }

        public Criteria andBuildIdNotEqualTo(Integer value) {
            addCriterion("build_id <>", value, "buildId");
            return this;
        }

        public Criteria andBuildIdGreaterThan(Integer value) {
            addCriterion("build_id >", value, "buildId");
            return this;
        }

        public Criteria andBuildIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("build_id >=", value, "buildId");
            return this;
        }

        public Criteria andBuildIdLessThan(Integer value) {
            addCriterion("build_id <", value, "buildId");
            return this;
        }

        public Criteria andBuildIdLessThanOrEqualTo(Integer value) {
            addCriterion("build_id <=", value, "buildId");
            return this;
        }

        public Criteria andBuildIdIn(List values) {
            addCriterion("build_id in", values, "buildId");
            return this;
        }

        public Criteria andBuildIdNotIn(List values) {
            addCriterion("build_id not in", values, "buildId");
            return this;
        }

        public Criteria andBuildIdBetween(Integer value1, Integer value2) {
            addCriterion("build_id between", value1, value2, "buildId");
            return this;
        }

        public Criteria andBuildIdNotBetween(Integer value1, Integer value2) {
            addCriterion("build_id not between", value1, value2, "buildId");
            return this;
        }

        public Criteria andPackageNameIsNull() {
            addCriterion("package_name is null");
            return this;
        }

        public Criteria andPackageNameIsNotNull() {
            addCriterion("package_name is not null");
            return this;
        }

        public Criteria andPackageNameEqualTo(String value) {
            addCriterion("package_name =", value, "packageName");
            return this;
        }

        public Criteria andPackageNameNotEqualTo(String value) {
            addCriterion("package_name <>", value, "packageName");
            return this;
        }

        public Criteria andPackageNameGreaterThan(String value) {
            addCriterion("package_name >", value, "packageName");
            return this;
        }

        public Criteria andPackageNameGreaterThanOrEqualTo(String value) {
            addCriterion("package_name >=", value, "packageName");
            return this;
        }

        public Criteria andPackageNameLessThan(String value) {
            addCriterion("package_name <", value, "packageName");
            return this;
        }

        public Criteria andPackageNameLessThanOrEqualTo(String value) {
            addCriterion("package_name <=", value, "packageName");
            return this;
        }

        public Criteria andPackageNameLike(String value) {
            addCriterion("package_name like", value, "packageName");
            return this;
        }

        public Criteria andPackageNameNotLike(String value) {
            addCriterion("package_name not like", value, "packageName");
            return this;
        }

        public Criteria andPackageNameIn(List values) {
            addCriterion("package_name in", values, "packageName");
            return this;
        }

        public Criteria andPackageNameNotIn(List values) {
            addCriterion("package_name not in", values, "packageName");
            return this;
        }

        public Criteria andPackageNameBetween(String value1, String value2) {
            addCriterion("package_name between", value1, value2, "packageName");
            return this;
        }

        public Criteria andPackageNameNotBetween(String value1, String value2) {
            addCriterion("package_name not between", value1, value2, "packageName");
            return this;
        }

        public Criteria andBeginTimeIsNull() {
            addCriterion("begin_time is null");
            return this;
        }

        public Criteria andBeginTimeIsNotNull() {
            addCriterion("begin_time is not null");
            return this;
        }

        public Criteria andBeginTimeEqualTo(Date value) {
            addCriterionForJDBCDate("begin_time =", value, "beginTime");
            return this;
        }

        public Criteria andBeginTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("begin_time <>", value, "beginTime");
            return this;
        }

        public Criteria andBeginTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("begin_time >", value, "beginTime");
            return this;
        }

        public Criteria andBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("begin_time >=", value, "beginTime");
            return this;
        }

        public Criteria andBeginTimeLessThan(Date value) {
            addCriterionForJDBCDate("begin_time <", value, "beginTime");
            return this;
        }

        public Criteria andBeginTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("begin_time <=", value, "beginTime");
            return this;
        }

        public Criteria andBeginTimeIn(List values) {
            addCriterionForJDBCDate("begin_time in", values, "beginTime");
            return this;
        }

        public Criteria andBeginTimeNotIn(List values) {
            addCriterionForJDBCDate("begin_time not in", values, "beginTime");
            return this;
        }

        public Criteria andBeginTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("begin_time between", value1, value2, "beginTime");
            return this;
        }

        public Criteria andBeginTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("begin_time not between", value1, value2, "beginTime");
            return this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterionForJDBCDate("end_time =", value, "endTime");
            return this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("end_time <>", value, "endTime");
            return this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("end_time >", value, "endTime");
            return this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("end_time >=", value, "endTime");
            return this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterionForJDBCDate("end_time <", value, "endTime");
            return this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("end_time <=", value, "endTime");
            return this;
        }

        public Criteria andEndTimeIn(List values) {
            addCriterionForJDBCDate("end_time in", values, "endTime");
            return this;
        }

        public Criteria andEndTimeNotIn(List values) {
            addCriterionForJDBCDate("end_time not in", values, "endTime");
            return this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("end_time between", value1, value2, "endTime");
            return this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("end_time not between", value1, value2, "endTime");
            return this;
        }

        public Criteria andCpPaymentUnitIsNull() {
            addCriterion("cp_payment_unit is null");
            return this;
        }

        public Criteria andCpPaymentUnitIsNotNull() {
            addCriterion("cp_payment_unit is not null");
            return this;
        }

        public Criteria andCpPaymentUnitEqualTo(BigDecimal value) {
            addCriterion("cp_payment_unit =", value, "cpPaymentUnit");
            return this;
        }

        public Criteria andCpPaymentUnitNotEqualTo(BigDecimal value) {
            addCriterion("cp_payment_unit <>", value, "cpPaymentUnit");
            return this;
        }

        public Criteria andCpPaymentUnitGreaterThan(BigDecimal value) {
            addCriterion("cp_payment_unit >", value, "cpPaymentUnit");
            return this;
        }

        public Criteria andCpPaymentUnitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cp_payment_unit >=", value, "cpPaymentUnit");
            return this;
        }

        public Criteria andCpPaymentUnitLessThan(BigDecimal value) {
            addCriterion("cp_payment_unit <", value, "cpPaymentUnit");
            return this;
        }

        public Criteria andCpPaymentUnitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cp_payment_unit <=", value, "cpPaymentUnit");
            return this;
        }

        public Criteria andCpPaymentUnitIn(List values) {
            addCriterion("cp_payment_unit in", values, "cpPaymentUnit");
            return this;
        }

        public Criteria andCpPaymentUnitNotIn(List values) {
            addCriterion("cp_payment_unit not in", values, "cpPaymentUnit");
            return this;
        }

        public Criteria andCpPaymentUnitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cp_payment_unit between", value1, value2, "cpPaymentUnit");
            return this;
        }

        public Criteria andCpPaymentUnitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cp_payment_unit not between", value1, value2, "cpPaymentUnit");
            return this;
        }

        public Criteria andChannelPaymentUnitIsNull() {
            addCriterion("channel_payment_unit is null");
            return this;
        }

        public Criteria andChannelPaymentUnitIsNotNull() {
            addCriterion("channel_payment_unit is not null");
            return this;
        }

        public Criteria andChannelPaymentUnitEqualTo(BigDecimal value) {
            addCriterion("channel_payment_unit =", value, "channelPaymentUnit");
            return this;
        }

        public Criteria andChannelPaymentUnitNotEqualTo(BigDecimal value) {
            addCriterion("channel_payment_unit <>", value, "channelPaymentUnit");
            return this;
        }

        public Criteria andChannelPaymentUnitGreaterThan(BigDecimal value) {
            addCriterion("channel_payment_unit >", value, "channelPaymentUnit");
            return this;
        }

        public Criteria andChannelPaymentUnitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("channel_payment_unit >=", value, "channelPaymentUnit");
            return this;
        }

        public Criteria andChannelPaymentUnitLessThan(BigDecimal value) {
            addCriterion("channel_payment_unit <", value, "channelPaymentUnit");
            return this;
        }

        public Criteria andChannelPaymentUnitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("channel_payment_unit <=", value, "channelPaymentUnit");
            return this;
        }

        public Criteria andChannelPaymentUnitIn(List values) {
            addCriterion("channel_payment_unit in", values, "channelPaymentUnit");
            return this;
        }

        public Criteria andChannelPaymentUnitNotIn(List values) {
            addCriterion("channel_payment_unit not in", values, "channelPaymentUnit");
            return this;
        }

        public Criteria andChannelPaymentUnitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("channel_payment_unit between", value1, value2, "channelPaymentUnit");
            return this;
        }

        public Criteria andChannelPaymentUnitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("channel_payment_unit not between", value1, value2, "channelPaymentUnit");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("status in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("status not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return this;
        }

        public Criteria andRemarkIn(List values) {
            addCriterion("remark in", values, "remark");
            return this;
        }

        public Criteria andRemarkNotIn(List values) {
            addCriterion("remark not in", values, "remark");
            return this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("create_time in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("create_time not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeIn(List values) {
            addCriterion("modify_time in", values, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotIn(List values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return this;
        }

        public Criteria andDeductionIsNull() {
            addCriterion("deduction is null");
            return this;
        }

        public Criteria andDeductionIsNotNull() {
            addCriterion("deduction is not null");
            return this;
        }

        public Criteria andDeductionEqualTo(String value) {
            addCriterion("deduction =", value, "deduction");
            return this;
        }

        public Criteria andDeductionNotEqualTo(String value) {
            addCriterion("deduction <>", value, "deduction");
            return this;
        }

        public Criteria andDeductionGreaterThan(String value) {
            addCriterion("deduction >", value, "deduction");
            return this;
        }

        public Criteria andDeductionGreaterThanOrEqualTo(String value) {
            addCriterion("deduction >=", value, "deduction");
            return this;
        }

        public Criteria andDeductionLessThan(String value) {
            addCriterion("deduction <", value, "deduction");
            return this;
        }

        public Criteria andDeductionLessThanOrEqualTo(String value) {
            addCriterion("deduction <=", value, "deduction");
            return this;
        }

        public Criteria andDeductionLike(String value) {
            addCriterion("deduction like", value, "deduction");
            return this;
        }

        public Criteria andDeductionNotLike(String value) {
            addCriterion("deduction not like", value, "deduction");
            return this;
        }

        public Criteria andDeductionIn(List values) {
            addCriterion("deduction in", values, "deduction");
            return this;
        }

        public Criteria andDeductionNotIn(List values) {
            addCriterion("deduction not in", values, "deduction");
            return this;
        }

        public Criteria andDeductionBetween(String value1, String value2) {
            addCriterion("deduction between", value1, value2, "deduction");
            return this;
        }

        public Criteria andDeductionNotBetween(String value1, String value2) {
            addCriterion("deduction not between", value1, value2, "deduction");
            return this;
        }

        public Criteria andAppnameIsNull() {
            addCriterion("appname is null");
            return this;
        }

        public Criteria andAppnameIsNotNull() {
            addCriterion("appname is not null");
            return this;
        }

        public Criteria andAppnameEqualTo(String value) {
            addCriterion("appname =", value, "appname");
            return this;
        }

        public Criteria andAppnameNotEqualTo(String value) {
            addCriterion("appname <>", value, "appname");
            return this;
        }

        public Criteria andAppnameGreaterThan(String value) {
            addCriterion("appname >", value, "appname");
            return this;
        }

        public Criteria andAppnameGreaterThanOrEqualTo(String value) {
            addCriterion("appname >=", value, "appname");
            return this;
        }

        public Criteria andAppnameLessThan(String value) {
            addCriterion("appname <", value, "appname");
            return this;
        }

        public Criteria andAppnameLessThanOrEqualTo(String value) {
            addCriterion("appname <=", value, "appname");
            return this;
        }

        public Criteria andAppnameLike(String value) {
            addCriterion("appname like", value, "appname");
            return this;
        }

        public Criteria andAppnameNotLike(String value) {
            addCriterion("appname not like", value, "appname");
            return this;
        }

        public Criteria andAppnameIn(List values) {
            addCriterion("appname in", values, "appname");
            return this;
        }

        public Criteria andAppnameNotIn(List values) {
            addCriterion("appname not in", values, "appname");
            return this;
        }

        public Criteria andAppnameBetween(String value1, String value2) {
            addCriterion("appname between", value1, value2, "appname");
            return this;
        }

        public Criteria andAppnameNotBetween(String value1, String value2) {
            addCriterion("appname not between", value1, value2, "appname");
            return this;
        }
    }
}