package com.wangli.data.analysis.ar.adc.module;

import java.util.Date;

public class DeviceAppAddInfo {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device_app_add_info.id
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device_app_add_info.user_id
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private Integer userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device_app_add_info.imei
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private String imei;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device_app_add_info.mac
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private String mac;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device_app_add_info.model
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private String model;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device_app_add_info.order_id
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private Integer orderId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device_app_add_info.pkg
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private String pkg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device_app_add_info.install_date
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private String installDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device_app_add_info.install_time
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private Date installTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device_app_add_info.identity_id
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private Integer identityId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device_app_add_info.identity_mark
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private Byte identityMark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device_app_add_info.channel_id
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private Integer channelId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device_app_add_info.receive_date
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private String receiveDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device_app_add_info.status
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device_app_add_info.insert_time
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    private Date insertTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device_app_add_info.id
     *
     * @return the value of device_app_add_info.id
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device_app_add_info.id
     *
     * @param id the value for device_app_add_info.id
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device_app_add_info.user_id
     *
     * @return the value of device_app_add_info.user_id
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device_app_add_info.user_id
     *
     * @param userId the value for device_app_add_info.user_id
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device_app_add_info.imei
     *
     * @return the value of device_app_add_info.imei
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device_app_add_info.imei
     *
     * @param imei the value for device_app_add_info.imei
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device_app_add_info.mac
     *
     * @return the value of device_app_add_info.mac
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device_app_add_info.mac
     *
     * @param mac the value for device_app_add_info.mac
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device_app_add_info.model
     *
     * @return the value of device_app_add_info.model
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device_app_add_info.model
     *
     * @param model the value for device_app_add_info.model
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device_app_add_info.order_id
     *
     * @return the value of device_app_add_info.order_id
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device_app_add_info.order_id
     *
     * @param orderId the value for device_app_add_info.order_id
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device_app_add_info.pkg
     *
     * @return the value of device_app_add_info.pkg
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public String getPkg() {
        return pkg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device_app_add_info.pkg
     *
     * @param pkg the value for device_app_add_info.pkg
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void setPkg(String pkg) {
        this.pkg = pkg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device_app_add_info.install_date
     *
     * @return the value of device_app_add_info.install_date
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public String getInstallDate() {
        return installDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device_app_add_info.install_date
     *
     * @param installDate the value for device_app_add_info.install_date
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void setInstallDate(String installDate) {
        this.installDate = installDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device_app_add_info.install_time
     *
     * @return the value of device_app_add_info.install_time
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public Date getInstallTime() {
        return installTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device_app_add_info.install_time
     *
     * @param installTime the value for device_app_add_info.install_time
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void setInstallTime(Date installTime) {
        this.installTime = installTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device_app_add_info.identity_id
     *
     * @return the value of device_app_add_info.identity_id
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public Integer getIdentityId() {
        return identityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device_app_add_info.identity_id
     *
     * @param identityId the value for device_app_add_info.identity_id
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void setIdentityId(Integer identityId) {
        this.identityId = identityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device_app_add_info.identity_mark
     *
     * @return the value of device_app_add_info.identity_mark
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public Byte getIdentityMark() {
        return identityMark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device_app_add_info.identity_mark
     *
     * @param identityMark the value for device_app_add_info.identity_mark
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void setIdentityMark(Byte identityMark) {
        this.identityMark = identityMark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device_app_add_info.channel_id
     *
     * @return the value of device_app_add_info.channel_id
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device_app_add_info.channel_id
     *
     * @param channelId the value for device_app_add_info.channel_id
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device_app_add_info.receive_date
     *
     * @return the value of device_app_add_info.receive_date
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public String getReceiveDate() {
        return receiveDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device_app_add_info.receive_date
     *
     * @param receiveDate the value for device_app_add_info.receive_date
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void setReceiveDate(String receiveDate) {
        this.receiveDate = receiveDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device_app_add_info.status
     *
     * @return the value of device_app_add_info.status
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device_app_add_info.status
     *
     * @param status the value for device_app_add_info.status
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device_app_add_info.insert_time
     *
     * @return the value of device_app_add_info.insert_time
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device_app_add_info.insert_time
     *
     * @param insertTime the value for device_app_add_info.insert_time
     *
     * @ibatorgenerated Thu Nov 13 10:39:11 CST 2014
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
}