package com.wangli.data.analysis.ar.adc.module;

public class DictIdentityStorage {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column dict_identity_storage.id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column dict_identity_storage.identity_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private Integer identityId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column dict_identity_storage.identity_mark
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private Byte identityMark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column dict_identity_storage.storage_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private Integer storageId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dict_identity_storage.id
     *
     * @return the value of dict_identity_storage.id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dict_identity_storage.id
     *
     * @param id the value for dict_identity_storage.id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dict_identity_storage.identity_id
     *
     * @return the value of dict_identity_storage.identity_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Integer getIdentityId() {
        return identityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dict_identity_storage.identity_id
     *
     * @param identityId the value for dict_identity_storage.identity_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setIdentityId(Integer identityId) {
        this.identityId = identityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dict_identity_storage.identity_mark
     *
     * @return the value of dict_identity_storage.identity_mark
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Byte getIdentityMark() {
        return identityMark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dict_identity_storage.identity_mark
     *
     * @param identityMark the value for dict_identity_storage.identity_mark
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setIdentityMark(Byte identityMark) {
        this.identityMark = identityMark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dict_identity_storage.storage_id
     *
     * @return the value of dict_identity_storage.storage_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Integer getStorageId() {
        return storageId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dict_identity_storage.storage_id
     *
     * @param storageId the value for dict_identity_storage.storage_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setStorageId(Integer storageId) {
        this.storageId = storageId;
    }
}