package com.wangli.data.analysis.ar.adc.module;

public class DictDeviceModel {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column dict_device_model.id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column dict_device_model.brand
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String brand;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column dict_device_model.model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String model;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dict_device_model.id
     *
     * @return the value of dict_device_model.id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dict_device_model.id
     *
     * @param id the value for dict_device_model.id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dict_device_model.brand
     *
     * @return the value of dict_device_model.brand
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dict_device_model.brand
     *
     * @param brand the value for dict_device_model.brand
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dict_device_model.model
     *
     * @return the value of dict_device_model.model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dict_device_model.model
     *
     * @param model the value for dict_device_model.model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setModel(String model) {
        this.model = model;
    }
}