package com.wangli.data.analysis.ar.adc.module;

import java.util.Date;

public class FactAppStat {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column fact_app_stat.id
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column fact_app_stat.data_time
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	private Date dataTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column fact_app_stat.order_id
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	private Integer orderId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column fact_app_stat.pkg
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	private String pkg;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column fact_app_stat.app_name
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	private String appName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column fact_app_stat.identity_id
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	private Integer identityId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column fact_app_stat.identity_mark
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	private Byte identityMark;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column fact_app_stat.channel_id
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	private Integer channelId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column fact_app_stat.model
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	private String model;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column fact_app_stat.install_count
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	private Integer installCount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column fact_app_stat.active_count
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	private Integer activeCount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column fact_app_stat.insert_time
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	private Date insertTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column fact_app_stat.user_id
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	private Integer userId;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column fact_app_stat.id
	 * @return  the value of fact_app_stat.id
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column fact_app_stat.id
	 * @param id  the value for fact_app_stat.id
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column fact_app_stat.data_time
	 * @return  the value of fact_app_stat.data_time
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public Date getDataTime() {
		return dataTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column fact_app_stat.data_time
	 * @param dataTime  the value for fact_app_stat.data_time
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public void setDataTime(Date dataTime) {
		this.dataTime = dataTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column fact_app_stat.order_id
	 * @return  the value of fact_app_stat.order_id
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column fact_app_stat.order_id
	 * @param orderId  the value for fact_app_stat.order_id
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column fact_app_stat.pkg
	 * @return  the value of fact_app_stat.pkg
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public String getPkg() {
		return pkg;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column fact_app_stat.pkg
	 * @param pkg  the value for fact_app_stat.pkg
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public void setPkg(String pkg) {
		this.pkg = pkg;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column fact_app_stat.app_name
	 * @return  the value of fact_app_stat.app_name
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public String getAppName() {
		return appName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column fact_app_stat.app_name
	 * @param appName  the value for fact_app_stat.app_name
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public void setAppName(String appName) {
		this.appName = appName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column fact_app_stat.identity_id
	 * @return  the value of fact_app_stat.identity_id
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public Integer getIdentityId() {
		return identityId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column fact_app_stat.identity_id
	 * @param identityId  the value for fact_app_stat.identity_id
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public void setIdentityId(Integer identityId) {
		this.identityId = identityId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column fact_app_stat.identity_mark
	 * @return  the value of fact_app_stat.identity_mark
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public Byte getIdentityMark() {
		return identityMark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column fact_app_stat.identity_mark
	 * @param identityMark  the value for fact_app_stat.identity_mark
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public void setIdentityMark(Byte identityMark) {
		this.identityMark = identityMark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column fact_app_stat.channel_id
	 * @return  the value of fact_app_stat.channel_id
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column fact_app_stat.channel_id
	 * @param channelId  the value for fact_app_stat.channel_id
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column fact_app_stat.model
	 * @return  the value of fact_app_stat.model
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public String getModel() {
		return model;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column fact_app_stat.model
	 * @param model  the value for fact_app_stat.model
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public void setModel(String model) {
		this.model = model;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column fact_app_stat.install_count
	 * @return  the value of fact_app_stat.install_count
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public Integer getInstallCount() {
		return installCount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column fact_app_stat.install_count
	 * @param installCount  the value for fact_app_stat.install_count
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public void setInstallCount(Integer installCount) {
		this.installCount = installCount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column fact_app_stat.active_count
	 * @return  the value of fact_app_stat.active_count
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public Integer getActiveCount() {
		return activeCount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column fact_app_stat.active_count
	 * @param activeCount  the value for fact_app_stat.active_count
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public void setActiveCount(Integer activeCount) {
		this.activeCount = activeCount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column fact_app_stat.insert_time
	 * @return  the value of fact_app_stat.insert_time
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column fact_app_stat.insert_time
	 * @param insertTime  the value for fact_app_stat.insert_time
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column fact_app_stat.user_id
	 * @return  the value of fact_app_stat.user_id
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column fact_app_stat.user_id
	 * @param userId  the value for fact_app_stat.user_id
	 * @ibatorgenerated  Wed Nov 12 18:48:06 CST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}