package com.wangli.data.analysis.ar.adc.module;

import java.util.Date;

public class InstallAppLog {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.user_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private Integer userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.tag_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private Integer tagId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.channel_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private Integer channelId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.order_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private Integer orderId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.pkg
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String pkg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.version
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String version;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.md5
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String md5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.brand
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String brand;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String model;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.imei
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String imei;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.mac
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String mac;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.serial_no
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String serialNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.android_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String androidId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.install_time
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private Date installTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.vid
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String vid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.pid
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String pid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.code
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private Byte code;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.install_system
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private Boolean installSystem;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.client_name
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String clientName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.client_version
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String clientVersion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.apk_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String apkTag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.apk_tag_channel
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private Integer apkTagChannel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.apk_tag_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private Integer apkTagOrder;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.create_time
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column install_app_log.error
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    private String error;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.id
     *
     * @return the value of install_app_log.id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.id
     *
     * @param id the value for install_app_log.id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.user_id
     *
     * @return the value of install_app_log.user_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.user_id
     *
     * @param userId the value for install_app_log.user_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.tag_id
     *
     * @return the value of install_app_log.tag_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.tag_id
     *
     * @param tagId the value for install_app_log.tag_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.channel_id
     *
     * @return the value of install_app_log.channel_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.channel_id
     *
     * @param channelId the value for install_app_log.channel_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.order_id
     *
     * @return the value of install_app_log.order_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.order_id
     *
     * @param orderId the value for install_app_log.order_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.pkg
     *
     * @return the value of install_app_log.pkg
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getPkg() {
        return pkg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.pkg
     *
     * @param pkg the value for install_app_log.pkg
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setPkg(String pkg) {
        this.pkg = pkg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.version
     *
     * @return the value of install_app_log.version
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.version
     *
     * @param version the value for install_app_log.version
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.md5
     *
     * @return the value of install_app_log.md5
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.md5
     *
     * @param md5 the value for install_app_log.md5
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setMd5(String md5) {
        this.md5 = md5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.brand
     *
     * @return the value of install_app_log.brand
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.brand
     *
     * @param brand the value for install_app_log.brand
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.model
     *
     * @return the value of install_app_log.model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.model
     *
     * @param model the value for install_app_log.model
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.imei
     *
     * @return the value of install_app_log.imei
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.imei
     *
     * @param imei the value for install_app_log.imei
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.mac
     *
     * @return the value of install_app_log.mac
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.mac
     *
     * @param mac the value for install_app_log.mac
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.serial_no
     *
     * @return the value of install_app_log.serial_no
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.serial_no
     *
     * @param serialNo the value for install_app_log.serial_no
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.android_id
     *
     * @return the value of install_app_log.android_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getAndroidId() {
        return androidId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.android_id
     *
     * @param androidId the value for install_app_log.android_id
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setAndroidId(String androidId) {
        this.androidId = androidId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.install_time
     *
     * @return the value of install_app_log.install_time
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Date getInstallTime() {
        return installTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.install_time
     *
     * @param installTime the value for install_app_log.install_time
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setInstallTime(Date installTime) {
        this.installTime = installTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.vid
     *
     * @return the value of install_app_log.vid
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getVid() {
        return vid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.vid
     *
     * @param vid the value for install_app_log.vid
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setVid(String vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.pid
     *
     * @return the value of install_app_log.pid
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.pid
     *
     * @param pid the value for install_app_log.pid
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.code
     *
     * @return the value of install_app_log.code
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Byte getCode() {
        return code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.code
     *
     * @param code the value for install_app_log.code
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setCode(Byte code) {
        this.code = code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.install_system
     *
     * @return the value of install_app_log.install_system
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Boolean getInstallSystem() {
        return installSystem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.install_system
     *
     * @param installSystem the value for install_app_log.install_system
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setInstallSystem(Boolean installSystem) {
        this.installSystem = installSystem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.client_name
     *
     * @return the value of install_app_log.client_name
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.client_name
     *
     * @param clientName the value for install_app_log.client_name
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.client_version
     *
     * @return the value of install_app_log.client_version
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getClientVersion() {
        return clientVersion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.client_version
     *
     * @param clientVersion the value for install_app_log.client_version
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setClientVersion(String clientVersion) {
        this.clientVersion = clientVersion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.apk_tag
     *
     * @return the value of install_app_log.apk_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getApkTag() {
        return apkTag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.apk_tag
     *
     * @param apkTag the value for install_app_log.apk_tag
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setApkTag(String apkTag) {
        this.apkTag = apkTag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.apk_tag_channel
     *
     * @return the value of install_app_log.apk_tag_channel
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Integer getApkTagChannel() {
        return apkTagChannel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.apk_tag_channel
     *
     * @param apkTagChannel the value for install_app_log.apk_tag_channel
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setApkTagChannel(Integer apkTagChannel) {
        this.apkTagChannel = apkTagChannel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.apk_tag_order
     *
     * @return the value of install_app_log.apk_tag_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Integer getApkTagOrder() {
        return apkTagOrder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.apk_tag_order
     *
     * @param apkTagOrder the value for install_app_log.apk_tag_order
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setApkTagOrder(Integer apkTagOrder) {
        this.apkTagOrder = apkTagOrder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.create_time
     *
     * @return the value of install_app_log.create_time
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.create_time
     *
     * @param createTime the value for install_app_log.create_time
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column install_app_log.error
     *
     * @return the value of install_app_log.error
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getError() {
        return error;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column install_app_log.error
     *
     * @param error the value for install_app_log.error
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setError(String error) {
        this.error = error;
    }
}