package com.wangli.data.analysis.ar.adc.module;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class InstallAppLogExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public InstallAppLogExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    protected InstallAppLogExample(InstallAppLogExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table install_app_log
     *
     * @ibatorgenerated Tue Nov 11 19:45:22 CST 2014
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return this;
        }

        public Criteria andUserIdIn(List values) {
            addCriterion("user_id in", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(List values) {
            addCriterion("user_id not in", values, "userId");
            return this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return this;
        }

        public Criteria andTagIdIsNull() {
            addCriterion("tag_id is null");
            return this;
        }

        public Criteria andTagIdIsNotNull() {
            addCriterion("tag_id is not null");
            return this;
        }

        public Criteria andTagIdEqualTo(Integer value) {
            addCriterion("tag_id =", value, "tagId");
            return this;
        }

        public Criteria andTagIdNotEqualTo(Integer value) {
            addCriterion("tag_id <>", value, "tagId");
            return this;
        }

        public Criteria andTagIdGreaterThan(Integer value) {
            addCriterion("tag_id >", value, "tagId");
            return this;
        }

        public Criteria andTagIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tag_id >=", value, "tagId");
            return this;
        }

        public Criteria andTagIdLessThan(Integer value) {
            addCriterion("tag_id <", value, "tagId");
            return this;
        }

        public Criteria andTagIdLessThanOrEqualTo(Integer value) {
            addCriterion("tag_id <=", value, "tagId");
            return this;
        }

        public Criteria andTagIdIn(List values) {
            addCriterion("tag_id in", values, "tagId");
            return this;
        }

        public Criteria andTagIdNotIn(List values) {
            addCriterion("tag_id not in", values, "tagId");
            return this;
        }

        public Criteria andTagIdBetween(Integer value1, Integer value2) {
            addCriterion("tag_id between", value1, value2, "tagId");
            return this;
        }

        public Criteria andTagIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tag_id not between", value1, value2, "tagId");
            return this;
        }

        public Criteria andChannelIdIsNull() {
            addCriterion("channel_id is null");
            return this;
        }

        public Criteria andChannelIdIsNotNull() {
            addCriterion("channel_id is not null");
            return this;
        }

        public Criteria andChannelIdEqualTo(Integer value) {
            addCriterion("channel_id =", value, "channelId");
            return this;
        }

        public Criteria andChannelIdNotEqualTo(Integer value) {
            addCriterion("channel_id <>", value, "channelId");
            return this;
        }

        public Criteria andChannelIdGreaterThan(Integer value) {
            addCriterion("channel_id >", value, "channelId");
            return this;
        }

        public Criteria andChannelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("channel_id >=", value, "channelId");
            return this;
        }

        public Criteria andChannelIdLessThan(Integer value) {
            addCriterion("channel_id <", value, "channelId");
            return this;
        }

        public Criteria andChannelIdLessThanOrEqualTo(Integer value) {
            addCriterion("channel_id <=", value, "channelId");
            return this;
        }

        public Criteria andChannelIdIn(List values) {
            addCriterion("channel_id in", values, "channelId");
            return this;
        }

        public Criteria andChannelIdNotIn(List values) {
            addCriterion("channel_id not in", values, "channelId");
            return this;
        }

        public Criteria andChannelIdBetween(Integer value1, Integer value2) {
            addCriterion("channel_id between", value1, value2, "channelId");
            return this;
        }

        public Criteria andChannelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("channel_id not between", value1, value2, "channelId");
            return this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("order_id =", value, "orderId");
            return this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "orderId");
            return this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("order_id >", value, "orderId");
            return this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "orderId");
            return this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("order_id <", value, "orderId");
            return this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "orderId");
            return this;
        }

        public Criteria andOrderIdIn(List values) {
            addCriterion("order_id in", values, "orderId");
            return this;
        }

        public Criteria andOrderIdNotIn(List values) {
            addCriterion("order_id not in", values, "orderId");
            return this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return this;
        }

        public Criteria andPkgIsNull() {
            addCriterion("pkg is null");
            return this;
        }

        public Criteria andPkgIsNotNull() {
            addCriterion("pkg is not null");
            return this;
        }

        public Criteria andPkgEqualTo(String value) {
            addCriterion("pkg =", value, "pkg");
            return this;
        }

        public Criteria andPkgNotEqualTo(String value) {
            addCriterion("pkg <>", value, "pkg");
            return this;
        }

        public Criteria andPkgGreaterThan(String value) {
            addCriterion("pkg >", value, "pkg");
            return this;
        }

        public Criteria andPkgGreaterThanOrEqualTo(String value) {
            addCriterion("pkg >=", value, "pkg");
            return this;
        }

        public Criteria andPkgLessThan(String value) {
            addCriterion("pkg <", value, "pkg");
            return this;
        }

        public Criteria andPkgLessThanOrEqualTo(String value) {
            addCriterion("pkg <=", value, "pkg");
            return this;
        }

        public Criteria andPkgLike(String value) {
            addCriterion("pkg like", value, "pkg");
            return this;
        }

        public Criteria andPkgNotLike(String value) {
            addCriterion("pkg not like", value, "pkg");
            return this;
        }

        public Criteria andPkgIn(List values) {
            addCriterion("pkg in", values, "pkg");
            return this;
        }

        public Criteria andPkgNotIn(List values) {
            addCriterion("pkg not in", values, "pkg");
            return this;
        }

        public Criteria andPkgBetween(String value1, String value2) {
            addCriterion("pkg between", value1, value2, "pkg");
            return this;
        }

        public Criteria andPkgNotBetween(String value1, String value2) {
            addCriterion("pkg not between", value1, value2, "pkg");
            return this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return this;
        }

        public Criteria andVersionIn(List values) {
            addCriterion("version in", values, "version");
            return this;
        }

        public Criteria andVersionNotIn(List values) {
            addCriterion("version not in", values, "version");
            return this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return this;
        }

        public Criteria andMd5IsNull() {
            addCriterion("md5 is null");
            return this;
        }

        public Criteria andMd5IsNotNull() {
            addCriterion("md5 is not null");
            return this;
        }

        public Criteria andMd5EqualTo(String value) {
            addCriterion("md5 =", value, "md5");
            return this;
        }

        public Criteria andMd5NotEqualTo(String value) {
            addCriterion("md5 <>", value, "md5");
            return this;
        }

        public Criteria andMd5GreaterThan(String value) {
            addCriterion("md5 >", value, "md5");
            return this;
        }

        public Criteria andMd5GreaterThanOrEqualTo(String value) {
            addCriterion("md5 >=", value, "md5");
            return this;
        }

        public Criteria andMd5LessThan(String value) {
            addCriterion("md5 <", value, "md5");
            return this;
        }

        public Criteria andMd5LessThanOrEqualTo(String value) {
            addCriterion("md5 <=", value, "md5");
            return this;
        }

        public Criteria andMd5Like(String value) {
            addCriterion("md5 like", value, "md5");
            return this;
        }

        public Criteria andMd5NotLike(String value) {
            addCriterion("md5 not like", value, "md5");
            return this;
        }

        public Criteria andMd5In(List values) {
            addCriterion("md5 in", values, "md5");
            return this;
        }

        public Criteria andMd5NotIn(List values) {
            addCriterion("md5 not in", values, "md5");
            return this;
        }

        public Criteria andMd5Between(String value1, String value2) {
            addCriterion("md5 between", value1, value2, "md5");
            return this;
        }

        public Criteria andMd5NotBetween(String value1, String value2) {
            addCriterion("md5 not between", value1, value2, "md5");
            return this;
        }

        public Criteria andBrandIsNull() {
            addCriterion("brand is null");
            return this;
        }

        public Criteria andBrandIsNotNull() {
            addCriterion("brand is not null");
            return this;
        }

        public Criteria andBrandEqualTo(String value) {
            addCriterion("brand =", value, "brand");
            return this;
        }

        public Criteria andBrandNotEqualTo(String value) {
            addCriterion("brand <>", value, "brand");
            return this;
        }

        public Criteria andBrandGreaterThan(String value) {
            addCriterion("brand >", value, "brand");
            return this;
        }

        public Criteria andBrandGreaterThanOrEqualTo(String value) {
            addCriterion("brand >=", value, "brand");
            return this;
        }

        public Criteria andBrandLessThan(String value) {
            addCriterion("brand <", value, "brand");
            return this;
        }

        public Criteria andBrandLessThanOrEqualTo(String value) {
            addCriterion("brand <=", value, "brand");
            return this;
        }

        public Criteria andBrandLike(String value) {
            addCriterion("brand like", value, "brand");
            return this;
        }

        public Criteria andBrandNotLike(String value) {
            addCriterion("brand not like", value, "brand");
            return this;
        }

        public Criteria andBrandIn(List values) {
            addCriterion("brand in", values, "brand");
            return this;
        }

        public Criteria andBrandNotIn(List values) {
            addCriterion("brand not in", values, "brand");
            return this;
        }

        public Criteria andBrandBetween(String value1, String value2) {
            addCriterion("brand between", value1, value2, "brand");
            return this;
        }

        public Criteria andBrandNotBetween(String value1, String value2) {
            addCriterion("brand not between", value1, value2, "brand");
            return this;
        }

        public Criteria andModelIsNull() {
            addCriterion("model is null");
            return this;
        }

        public Criteria andModelIsNotNull() {
            addCriterion("model is not null");
            return this;
        }

        public Criteria andModelEqualTo(String value) {
            addCriterion("model =", value, "model");
            return this;
        }

        public Criteria andModelNotEqualTo(String value) {
            addCriterion("model <>", value, "model");
            return this;
        }

        public Criteria andModelGreaterThan(String value) {
            addCriterion("model >", value, "model");
            return this;
        }

        public Criteria andModelGreaterThanOrEqualTo(String value) {
            addCriterion("model >=", value, "model");
            return this;
        }

        public Criteria andModelLessThan(String value) {
            addCriterion("model <", value, "model");
            return this;
        }

        public Criteria andModelLessThanOrEqualTo(String value) {
            addCriterion("model <=", value, "model");
            return this;
        }

        public Criteria andModelLike(String value) {
            addCriterion("model like", value, "model");
            return this;
        }

        public Criteria andModelNotLike(String value) {
            addCriterion("model not like", value, "model");
            return this;
        }

        public Criteria andModelIn(List values) {
            addCriterion("model in", values, "model");
            return this;
        }

        public Criteria andModelNotIn(List values) {
            addCriterion("model not in", values, "model");
            return this;
        }

        public Criteria andModelBetween(String value1, String value2) {
            addCriterion("model between", value1, value2, "model");
            return this;
        }

        public Criteria andModelNotBetween(String value1, String value2) {
            addCriterion("model not between", value1, value2, "model");
            return this;
        }

        public Criteria andImeiIsNull() {
            addCriterion("imei is null");
            return this;
        }

        public Criteria andImeiIsNotNull() {
            addCriterion("imei is not null");
            return this;
        }

        public Criteria andImeiEqualTo(String value) {
            addCriterion("imei =", value, "imei");
            return this;
        }

        public Criteria andImeiNotEqualTo(String value) {
            addCriterion("imei <>", value, "imei");
            return this;
        }

        public Criteria andImeiGreaterThan(String value) {
            addCriterion("imei >", value, "imei");
            return this;
        }

        public Criteria andImeiGreaterThanOrEqualTo(String value) {
            addCriterion("imei >=", value, "imei");
            return this;
        }

        public Criteria andImeiLessThan(String value) {
            addCriterion("imei <", value, "imei");
            return this;
        }

        public Criteria andImeiLessThanOrEqualTo(String value) {
            addCriterion("imei <=", value, "imei");
            return this;
        }

        public Criteria andImeiLike(String value) {
            addCriterion("imei like", value, "imei");
            return this;
        }

        public Criteria andImeiNotLike(String value) {
            addCriterion("imei not like", value, "imei");
            return this;
        }

        public Criteria andImeiIn(List values) {
            addCriterion("imei in", values, "imei");
            return this;
        }

        public Criteria andImeiNotIn(List values) {
            addCriterion("imei not in", values, "imei");
            return this;
        }

        public Criteria andImeiBetween(String value1, String value2) {
            addCriterion("imei between", value1, value2, "imei");
            return this;
        }

        public Criteria andImeiNotBetween(String value1, String value2) {
            addCriterion("imei not between", value1, value2, "imei");
            return this;
        }

        public Criteria andMacIsNull() {
            addCriterion("mac is null");
            return this;
        }

        public Criteria andMacIsNotNull() {
            addCriterion("mac is not null");
            return this;
        }

        public Criteria andMacEqualTo(String value) {
            addCriterion("mac =", value, "mac");
            return this;
        }

        public Criteria andMacNotEqualTo(String value) {
            addCriterion("mac <>", value, "mac");
            return this;
        }

        public Criteria andMacGreaterThan(String value) {
            addCriterion("mac >", value, "mac");
            return this;
        }

        public Criteria andMacGreaterThanOrEqualTo(String value) {
            addCriterion("mac >=", value, "mac");
            return this;
        }

        public Criteria andMacLessThan(String value) {
            addCriterion("mac <", value, "mac");
            return this;
        }

        public Criteria andMacLessThanOrEqualTo(String value) {
            addCriterion("mac <=", value, "mac");
            return this;
        }

        public Criteria andMacLike(String value) {
            addCriterion("mac like", value, "mac");
            return this;
        }

        public Criteria andMacNotLike(String value) {
            addCriterion("mac not like", value, "mac");
            return this;
        }

        public Criteria andMacIn(List values) {
            addCriterion("mac in", values, "mac");
            return this;
        }

        public Criteria andMacNotIn(List values) {
            addCriterion("mac not in", values, "mac");
            return this;
        }

        public Criteria andMacBetween(String value1, String value2) {
            addCriterion("mac between", value1, value2, "mac");
            return this;
        }

        public Criteria andMacNotBetween(String value1, String value2) {
            addCriterion("mac not between", value1, value2, "mac");
            return this;
        }

        public Criteria andSerialNoIsNull() {
            addCriterion("serial_no is null");
            return this;
        }

        public Criteria andSerialNoIsNotNull() {
            addCriterion("serial_no is not null");
            return this;
        }

        public Criteria andSerialNoEqualTo(String value) {
            addCriterion("serial_no =", value, "serialNo");
            return this;
        }

        public Criteria andSerialNoNotEqualTo(String value) {
            addCriterion("serial_no <>", value, "serialNo");
            return this;
        }

        public Criteria andSerialNoGreaterThan(String value) {
            addCriterion("serial_no >", value, "serialNo");
            return this;
        }

        public Criteria andSerialNoGreaterThanOrEqualTo(String value) {
            addCriterion("serial_no >=", value, "serialNo");
            return this;
        }

        public Criteria andSerialNoLessThan(String value) {
            addCriterion("serial_no <", value, "serialNo");
            return this;
        }

        public Criteria andSerialNoLessThanOrEqualTo(String value) {
            addCriterion("serial_no <=", value, "serialNo");
            return this;
        }

        public Criteria andSerialNoLike(String value) {
            addCriterion("serial_no like", value, "serialNo");
            return this;
        }

        public Criteria andSerialNoNotLike(String value) {
            addCriterion("serial_no not like", value, "serialNo");
            return this;
        }

        public Criteria andSerialNoIn(List values) {
            addCriterion("serial_no in", values, "serialNo");
            return this;
        }

        public Criteria andSerialNoNotIn(List values) {
            addCriterion("serial_no not in", values, "serialNo");
            return this;
        }

        public Criteria andSerialNoBetween(String value1, String value2) {
            addCriterion("serial_no between", value1, value2, "serialNo");
            return this;
        }

        public Criteria andSerialNoNotBetween(String value1, String value2) {
            addCriterion("serial_no not between", value1, value2, "serialNo");
            return this;
        }

        public Criteria andAndroidIdIsNull() {
            addCriterion("android_id is null");
            return this;
        }

        public Criteria andAndroidIdIsNotNull() {
            addCriterion("android_id is not null");
            return this;
        }

        public Criteria andAndroidIdEqualTo(String value) {
            addCriterion("android_id =", value, "androidId");
            return this;
        }

        public Criteria andAndroidIdNotEqualTo(String value) {
            addCriterion("android_id <>", value, "androidId");
            return this;
        }

        public Criteria andAndroidIdGreaterThan(String value) {
            addCriterion("android_id >", value, "androidId");
            return this;
        }

        public Criteria andAndroidIdGreaterThanOrEqualTo(String value) {
            addCriterion("android_id >=", value, "androidId");
            return this;
        }

        public Criteria andAndroidIdLessThan(String value) {
            addCriterion("android_id <", value, "androidId");
            return this;
        }

        public Criteria andAndroidIdLessThanOrEqualTo(String value) {
            addCriterion("android_id <=", value, "androidId");
            return this;
        }

        public Criteria andAndroidIdLike(String value) {
            addCriterion("android_id like", value, "androidId");
            return this;
        }

        public Criteria andAndroidIdNotLike(String value) {
            addCriterion("android_id not like", value, "androidId");
            return this;
        }

        public Criteria andAndroidIdIn(List values) {
            addCriterion("android_id in", values, "androidId");
            return this;
        }

        public Criteria andAndroidIdNotIn(List values) {
            addCriterion("android_id not in", values, "androidId");
            return this;
        }

        public Criteria andAndroidIdBetween(String value1, String value2) {
            addCriterion("android_id between", value1, value2, "androidId");
            return this;
        }

        public Criteria andAndroidIdNotBetween(String value1, String value2) {
            addCriterion("android_id not between", value1, value2, "androidId");
            return this;
        }

        public Criteria andInstallTimeIsNull() {
            addCriterion("install_time is null");
            return this;
        }

        public Criteria andInstallTimeIsNotNull() {
            addCriterion("install_time is not null");
            return this;
        }

        public Criteria andInstallTimeEqualTo(Date value) {
            addCriterion("install_time =", value, "installTime");
            return this;
        }

        public Criteria andInstallTimeNotEqualTo(Date value) {
            addCriterion("install_time <>", value, "installTime");
            return this;
        }

        public Criteria andInstallTimeGreaterThan(Date value) {
            addCriterion("install_time >", value, "installTime");
            return this;
        }

        public Criteria andInstallTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("install_time >=", value, "installTime");
            return this;
        }

        public Criteria andInstallTimeLessThan(Date value) {
            addCriterion("install_time <", value, "installTime");
            return this;
        }

        public Criteria andInstallTimeLessThanOrEqualTo(Date value) {
            addCriterion("install_time <=", value, "installTime");
            return this;
        }

        public Criteria andInstallTimeIn(List values) {
            addCriterion("install_time in", values, "installTime");
            return this;
        }

        public Criteria andInstallTimeNotIn(List values) {
            addCriterion("install_time not in", values, "installTime");
            return this;
        }

        public Criteria andInstallTimeBetween(Date value1, Date value2) {
            addCriterion("install_time between", value1, value2, "installTime");
            return this;
        }

        public Criteria andInstallTimeNotBetween(Date value1, Date value2) {
            addCriterion("install_time not between", value1, value2, "installTime");
            return this;
        }

        public Criteria andVidIsNull() {
            addCriterion("vid is null");
            return this;
        }

        public Criteria andVidIsNotNull() {
            addCriterion("vid is not null");
            return this;
        }

        public Criteria andVidEqualTo(String value) {
            addCriterion("vid =", value, "vid");
            return this;
        }

        public Criteria andVidNotEqualTo(String value) {
            addCriterion("vid <>", value, "vid");
            return this;
        }

        public Criteria andVidGreaterThan(String value) {
            addCriterion("vid >", value, "vid");
            return this;
        }

        public Criteria andVidGreaterThanOrEqualTo(String value) {
            addCriterion("vid >=", value, "vid");
            return this;
        }

        public Criteria andVidLessThan(String value) {
            addCriterion("vid <", value, "vid");
            return this;
        }

        public Criteria andVidLessThanOrEqualTo(String value) {
            addCriterion("vid <=", value, "vid");
            return this;
        }

        public Criteria andVidLike(String value) {
            addCriterion("vid like", value, "vid");
            return this;
        }

        public Criteria andVidNotLike(String value) {
            addCriterion("vid not like", value, "vid");
            return this;
        }

        public Criteria andVidIn(List values) {
            addCriterion("vid in", values, "vid");
            return this;
        }

        public Criteria andVidNotIn(List values) {
            addCriterion("vid not in", values, "vid");
            return this;
        }

        public Criteria andVidBetween(String value1, String value2) {
            addCriterion("vid between", value1, value2, "vid");
            return this;
        }

        public Criteria andVidNotBetween(String value1, String value2) {
            addCriterion("vid not between", value1, value2, "vid");
            return this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return this;
        }

        public Criteria andPidEqualTo(String value) {
            addCriterion("pid =", value, "pid");
            return this;
        }

        public Criteria andPidNotEqualTo(String value) {
            addCriterion("pid <>", value, "pid");
            return this;
        }

        public Criteria andPidGreaterThan(String value) {
            addCriterion("pid >", value, "pid");
            return this;
        }

        public Criteria andPidGreaterThanOrEqualTo(String value) {
            addCriterion("pid >=", value, "pid");
            return this;
        }

        public Criteria andPidLessThan(String value) {
            addCriterion("pid <", value, "pid");
            return this;
        }

        public Criteria andPidLessThanOrEqualTo(String value) {
            addCriterion("pid <=", value, "pid");
            return this;
        }

        public Criteria andPidLike(String value) {
            addCriterion("pid like", value, "pid");
            return this;
        }

        public Criteria andPidNotLike(String value) {
            addCriterion("pid not like", value, "pid");
            return this;
        }

        public Criteria andPidIn(List values) {
            addCriterion("pid in", values, "pid");
            return this;
        }

        public Criteria andPidNotIn(List values) {
            addCriterion("pid not in", values, "pid");
            return this;
        }

        public Criteria andPidBetween(String value1, String value2) {
            addCriterion("pid between", value1, value2, "pid");
            return this;
        }

        public Criteria andPidNotBetween(String value1, String value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return this;
        }

        public Criteria andCodeEqualTo(Byte value) {
            addCriterion("code =", value, "code");
            return this;
        }

        public Criteria andCodeNotEqualTo(Byte value) {
            addCriterion("code <>", value, "code");
            return this;
        }

        public Criteria andCodeGreaterThan(Byte value) {
            addCriterion("code >", value, "code");
            return this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(Byte value) {
            addCriterion("code >=", value, "code");
            return this;
        }

        public Criteria andCodeLessThan(Byte value) {
            addCriterion("code <", value, "code");
            return this;
        }

        public Criteria andCodeLessThanOrEqualTo(Byte value) {
            addCriterion("code <=", value, "code");
            return this;
        }

        public Criteria andCodeIn(List values) {
            addCriterion("code in", values, "code");
            return this;
        }

        public Criteria andCodeNotIn(List values) {
            addCriterion("code not in", values, "code");
            return this;
        }

        public Criteria andCodeBetween(Byte value1, Byte value2) {
            addCriterion("code between", value1, value2, "code");
            return this;
        }

        public Criteria andCodeNotBetween(Byte value1, Byte value2) {
            addCriterion("code not between", value1, value2, "code");
            return this;
        }

        public Criteria andInstallSystemIsNull() {
            addCriterion("install_system is null");
            return this;
        }

        public Criteria andInstallSystemIsNotNull() {
            addCriterion("install_system is not null");
            return this;
        }

        public Criteria andInstallSystemEqualTo(Boolean value) {
            addCriterion("install_system =", value, "installSystem");
            return this;
        }

        public Criteria andInstallSystemNotEqualTo(Boolean value) {
            addCriterion("install_system <>", value, "installSystem");
            return this;
        }

        public Criteria andInstallSystemGreaterThan(Boolean value) {
            addCriterion("install_system >", value, "installSystem");
            return this;
        }

        public Criteria andInstallSystemGreaterThanOrEqualTo(Boolean value) {
            addCriterion("install_system >=", value, "installSystem");
            return this;
        }

        public Criteria andInstallSystemLessThan(Boolean value) {
            addCriterion("install_system <", value, "installSystem");
            return this;
        }

        public Criteria andInstallSystemLessThanOrEqualTo(Boolean value) {
            addCriterion("install_system <=", value, "installSystem");
            return this;
        }

        public Criteria andInstallSystemIn(List values) {
            addCriterion("install_system in", values, "installSystem");
            return this;
        }

        public Criteria andInstallSystemNotIn(List values) {
            addCriterion("install_system not in", values, "installSystem");
            return this;
        }

        public Criteria andInstallSystemBetween(Boolean value1, Boolean value2) {
            addCriterion("install_system between", value1, value2, "installSystem");
            return this;
        }

        public Criteria andInstallSystemNotBetween(Boolean value1, Boolean value2) {
            addCriterion("install_system not between", value1, value2, "installSystem");
            return this;
        }

        public Criteria andClientNameIsNull() {
            addCriterion("client_name is null");
            return this;
        }

        public Criteria andClientNameIsNotNull() {
            addCriterion("client_name is not null");
            return this;
        }

        public Criteria andClientNameEqualTo(String value) {
            addCriterion("client_name =", value, "clientName");
            return this;
        }

        public Criteria andClientNameNotEqualTo(String value) {
            addCriterion("client_name <>", value, "clientName");
            return this;
        }

        public Criteria andClientNameGreaterThan(String value) {
            addCriterion("client_name >", value, "clientName");
            return this;
        }

        public Criteria andClientNameGreaterThanOrEqualTo(String value) {
            addCriterion("client_name >=", value, "clientName");
            return this;
        }

        public Criteria andClientNameLessThan(String value) {
            addCriterion("client_name <", value, "clientName");
            return this;
        }

        public Criteria andClientNameLessThanOrEqualTo(String value) {
            addCriterion("client_name <=", value, "clientName");
            return this;
        }

        public Criteria andClientNameLike(String value) {
            addCriterion("client_name like", value, "clientName");
            return this;
        }

        public Criteria andClientNameNotLike(String value) {
            addCriterion("client_name not like", value, "clientName");
            return this;
        }

        public Criteria andClientNameIn(List values) {
            addCriterion("client_name in", values, "clientName");
            return this;
        }

        public Criteria andClientNameNotIn(List values) {
            addCriterion("client_name not in", values, "clientName");
            return this;
        }

        public Criteria andClientNameBetween(String value1, String value2) {
            addCriterion("client_name between", value1, value2, "clientName");
            return this;
        }

        public Criteria andClientNameNotBetween(String value1, String value2) {
            addCriterion("client_name not between", value1, value2, "clientName");
            return this;
        }

        public Criteria andClientVersionIsNull() {
            addCriterion("client_version is null");
            return this;
        }

        public Criteria andClientVersionIsNotNull() {
            addCriterion("client_version is not null");
            return this;
        }

        public Criteria andClientVersionEqualTo(String value) {
            addCriterion("client_version =", value, "clientVersion");
            return this;
        }

        public Criteria andClientVersionNotEqualTo(String value) {
            addCriterion("client_version <>", value, "clientVersion");
            return this;
        }

        public Criteria andClientVersionGreaterThan(String value) {
            addCriterion("client_version >", value, "clientVersion");
            return this;
        }

        public Criteria andClientVersionGreaterThanOrEqualTo(String value) {
            addCriterion("client_version >=", value, "clientVersion");
            return this;
        }

        public Criteria andClientVersionLessThan(String value) {
            addCriterion("client_version <", value, "clientVersion");
            return this;
        }

        public Criteria andClientVersionLessThanOrEqualTo(String value) {
            addCriterion("client_version <=", value, "clientVersion");
            return this;
        }

        public Criteria andClientVersionLike(String value) {
            addCriterion("client_version like", value, "clientVersion");
            return this;
        }

        public Criteria andClientVersionNotLike(String value) {
            addCriterion("client_version not like", value, "clientVersion");
            return this;
        }

        public Criteria andClientVersionIn(List values) {
            addCriterion("client_version in", values, "clientVersion");
            return this;
        }

        public Criteria andClientVersionNotIn(List values) {
            addCriterion("client_version not in", values, "clientVersion");
            return this;
        }

        public Criteria andClientVersionBetween(String value1, String value2) {
            addCriterion("client_version between", value1, value2, "clientVersion");
            return this;
        }

        public Criteria andClientVersionNotBetween(String value1, String value2) {
            addCriterion("client_version not between", value1, value2, "clientVersion");
            return this;
        }

        public Criteria andApkTagIsNull() {
            addCriterion("apk_tag is null");
            return this;
        }

        public Criteria andApkTagIsNotNull() {
            addCriterion("apk_tag is not null");
            return this;
        }

        public Criteria andApkTagEqualTo(String value) {
            addCriterion("apk_tag =", value, "apkTag");
            return this;
        }

        public Criteria andApkTagNotEqualTo(String value) {
            addCriterion("apk_tag <>", value, "apkTag");
            return this;
        }

        public Criteria andApkTagGreaterThan(String value) {
            addCriterion("apk_tag >", value, "apkTag");
            return this;
        }

        public Criteria andApkTagGreaterThanOrEqualTo(String value) {
            addCriterion("apk_tag >=", value, "apkTag");
            return this;
        }

        public Criteria andApkTagLessThan(String value) {
            addCriterion("apk_tag <", value, "apkTag");
            return this;
        }

        public Criteria andApkTagLessThanOrEqualTo(String value) {
            addCriterion("apk_tag <=", value, "apkTag");
            return this;
        }

        public Criteria andApkTagLike(String value) {
            addCriterion("apk_tag like", value, "apkTag");
            return this;
        }

        public Criteria andApkTagNotLike(String value) {
            addCriterion("apk_tag not like", value, "apkTag");
            return this;
        }

        public Criteria andApkTagIn(List values) {
            addCriterion("apk_tag in", values, "apkTag");
            return this;
        }

        public Criteria andApkTagNotIn(List values) {
            addCriterion("apk_tag not in", values, "apkTag");
            return this;
        }

        public Criteria andApkTagBetween(String value1, String value2) {
            addCriterion("apk_tag between", value1, value2, "apkTag");
            return this;
        }

        public Criteria andApkTagNotBetween(String value1, String value2) {
            addCriterion("apk_tag not between", value1, value2, "apkTag");
            return this;
        }

        public Criteria andApkTagChannelIsNull() {
            addCriterion("apk_tag_channel is null");
            return this;
        }

        public Criteria andApkTagChannelIsNotNull() {
            addCriterion("apk_tag_channel is not null");
            return this;
        }

        public Criteria andApkTagChannelEqualTo(Integer value) {
            addCriterion("apk_tag_channel =", value, "apkTagChannel");
            return this;
        }

        public Criteria andApkTagChannelNotEqualTo(Integer value) {
            addCriterion("apk_tag_channel <>", value, "apkTagChannel");
            return this;
        }

        public Criteria andApkTagChannelGreaterThan(Integer value) {
            addCriterion("apk_tag_channel >", value, "apkTagChannel");
            return this;
        }

        public Criteria andApkTagChannelGreaterThanOrEqualTo(Integer value) {
            addCriterion("apk_tag_channel >=", value, "apkTagChannel");
            return this;
        }

        public Criteria andApkTagChannelLessThan(Integer value) {
            addCriterion("apk_tag_channel <", value, "apkTagChannel");
            return this;
        }

        public Criteria andApkTagChannelLessThanOrEqualTo(Integer value) {
            addCriterion("apk_tag_channel <=", value, "apkTagChannel");
            return this;
        }

        public Criteria andApkTagChannelIn(List values) {
            addCriterion("apk_tag_channel in", values, "apkTagChannel");
            return this;
        }

        public Criteria andApkTagChannelNotIn(List values) {
            addCriterion("apk_tag_channel not in", values, "apkTagChannel");
            return this;
        }

        public Criteria andApkTagChannelBetween(Integer value1, Integer value2) {
            addCriterion("apk_tag_channel between", value1, value2, "apkTagChannel");
            return this;
        }

        public Criteria andApkTagChannelNotBetween(Integer value1, Integer value2) {
            addCriterion("apk_tag_channel not between", value1, value2, "apkTagChannel");
            return this;
        }

        public Criteria andApkTagOrderIsNull() {
            addCriterion("apk_tag_order is null");
            return this;
        }

        public Criteria andApkTagOrderIsNotNull() {
            addCriterion("apk_tag_order is not null");
            return this;
        }

        public Criteria andApkTagOrderEqualTo(Integer value) {
            addCriterion("apk_tag_order =", value, "apkTagOrder");
            return this;
        }

        public Criteria andApkTagOrderNotEqualTo(Integer value) {
            addCriterion("apk_tag_order <>", value, "apkTagOrder");
            return this;
        }

        public Criteria andApkTagOrderGreaterThan(Integer value) {
            addCriterion("apk_tag_order >", value, "apkTagOrder");
            return this;
        }

        public Criteria andApkTagOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("apk_tag_order >=", value, "apkTagOrder");
            return this;
        }

        public Criteria andApkTagOrderLessThan(Integer value) {
            addCriterion("apk_tag_order <", value, "apkTagOrder");
            return this;
        }

        public Criteria andApkTagOrderLessThanOrEqualTo(Integer value) {
            addCriterion("apk_tag_order <=", value, "apkTagOrder");
            return this;
        }

        public Criteria andApkTagOrderIn(List values) {
            addCriterion("apk_tag_order in", values, "apkTagOrder");
            return this;
        }

        public Criteria andApkTagOrderNotIn(List values) {
            addCriterion("apk_tag_order not in", values, "apkTagOrder");
            return this;
        }

        public Criteria andApkTagOrderBetween(Integer value1, Integer value2) {
            addCriterion("apk_tag_order between", value1, value2, "apkTagOrder");
            return this;
        }

        public Criteria andApkTagOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("apk_tag_order not between", value1, value2, "apkTagOrder");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("create_time in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("create_time not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return this;
        }
    }
}